//go:build !grammar_subset || grammar_subset_bass

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package bass provides the standalone bass grammar.
package bass

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "79393e4d52e2e0ce24e835e4bdde707b9af676631c56d6d9c4dee1513943f9c5"

func init() { ; grammarruntime.RegisterBlob("bass", grammarblobs.Bass) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("bass") }
