//go:build !grammar_subset || grammar_subset_crystal

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package crystal provides the standalone crystal grammar.
package crystal

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3fabcc89397e4fc24a25d6994e1a4b63860ce7245bc4fa494162e4e0f0ec5321"

func init() {
	grammarruntime.RegisterCrystalSupport()
	grammarruntime.RegisterBlob("crystal", grammarblobs.Crystal)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("crystal.bin") }
