//go:build !grammar_subset || grammar_subset_make

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package make provides the standalone make grammar.
package make

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7c97455dd197475218b426a133dfcc3deac7b6cdd918434e64a72349ce4f2c3e"

func init() { ; grammarruntime.RegisterBlob("make", grammarblobs.Make) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("make.bin") }
