//go:build !grammar_subset || grammar_subset_hcl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package hcl provides the standalone hcl grammar.
package hcl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ad180aa164b21d132b43838100b49206587f08bf7972cc19ccc9519eca9195e9"

func init() {
	grammarruntime.RegisterHclSupport()
	grammarruntime.RegisterBlob("hcl", grammarblobs.Hcl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("hcl") }
