//go:build !grammar_subset || grammar_subset_xml

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package xml provides the standalone xml grammar.
package xml

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "79ffeb5ce06cc3ac94ea25775676c16d2f2ece30c37c3c2c9b47b15425f0d068"

func init() {
	grammarruntime.RegisterXmlSupport()
	grammarruntime.RegisterBlob("xml", grammarblobs.Xml)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("xml.bin") }
