//go:build !grammar_subset || grammar_subset_properties

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package properties provides the standalone properties grammar.
package properties

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8cd02316e759eefaa518f5e28165e859937f486dac829efcca6dde5144bf56df"

func init() {
	grammarruntime.RegisterPropertiesSupport()
	grammarruntime.RegisterBlob("properties", grammarblobs.Properties)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("properties.bin") }
