//go:build !grammar_subset || grammar_subset_properties

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package properties provides the standalone properties grammar.
package properties

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1df359dc582574d9003bf02bc24f9cddff85a758922d0af3ed3ff3f3f8d28f79"

func init() {
	grammarruntime.RegisterPropertiesSupport()
	grammarruntime.RegisterBlob("properties", grammarblobs.Properties)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("properties") }
