//go:build !grammar_subset || grammar_subset_eds

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package eds provides the standalone eds grammar.
package eds

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b4faed5e175adbe9caa5bf7d474ef492c43cc24408aff6eb4b29a821cc6015c7"

func init() { ; grammarruntime.RegisterBlob("eds", grammarblobs.Eds) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("eds") }
