//go:build !grammar_subset || grammar_subset_vue

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package vue provides the standalone vue grammar.
package vue

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "266c64ab69338824e5cc801e126c3830e33ec4b157d4f3a9c472085e92cd41f5"

func init() {
	grammarruntime.RegisterVueSupport()
	grammarruntime.RegisterBlob("vue", grammarblobs.Vue)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("vue.bin") }
