//go:build !grammar_subset || grammar_subset_twig

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package twig provides the standalone twig grammar.
package twig

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "679be5b56b5ccd665e4233cfbf1256b56bc7b8984be1c40e13872c7dbd3d0a1a"

func init() { ; grammarruntime.RegisterBlob("twig", grammarblobs.Twig) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("twig") }
