//go:build !grammar_subset || grammar_subset_twig

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package twig provides the standalone twig grammar.
package twig

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2a854ddd010251b62e52481cab60ef31e4ad79c52463145b2f5a3789b4127ff9"

func init() { ; grammarruntime.RegisterBlob("twig", grammarblobs.Twig) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("twig.bin") }
