//go:build !grammar_subset || grammar_subset_ebnf

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ebnf provides the standalone ebnf grammar.
package ebnf

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "6706c12308f7e4d2547ea008ae7f134edadc7fd6e31b03a42e186df52ff7c58c"

func init() { ; grammarruntime.RegisterBlob("ebnf", grammarblobs.Ebnf) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ebnf.bin") }
