//go:build !grammar_subset || grammar_subset_gleam

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package gleam provides the standalone gleam grammar.
package gleam

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "752de405186bb191f9c2508da6208d7e60ae6a42068ab528ec1627fe81c1adf8"

func init() {
	grammarruntime.RegisterGleamSupport()
	grammarruntime.RegisterBlob("gleam", grammarblobs.Gleam)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("gleam") }
