//go:build !grammar_subset || grammar_subset_cue

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cue provides the standalone cue grammar.
package cue

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3ff52c09bc788d87116ec56070c4733829513c3d3beadc9028ea4ef7b1d3609a"

func init() {
	grammarruntime.RegisterCueSupport()
	grammarruntime.RegisterBlob("cue", grammarblobs.Cue)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cue.bin") }
