//go:build !grammar_subset || grammar_subset_ssh_config

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ssh_config provides the standalone ssh_config grammar.
package ssh_config

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ed2aabd2cdfd6fa95713bc0e608c5df6955d52dc8ab3f25bf4e7a944a0d59599"

func init() { ; grammarruntime.RegisterBlob("ssh_config", grammarblobs.Ssh_config) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ssh_config.bin") }
