//go:build !grammar_subset || grammar_subset_ssh_config

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ssh_config provides the standalone ssh_config grammar.
package ssh_config

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "eb7f25034477675aec9667764f949ac65e167db3e56592034c1756091c4a5f79"

func init() { ; grammarruntime.RegisterBlob("ssh_config", grammarblobs.Ssh_config) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ssh_config.bin") }
