//go:build !grammar_subset || grammar_subset_editorconfig

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package editorconfig provides the standalone editorconfig grammar.
package editorconfig

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a195c8b8fc22e578eea8aa1f2332884a62c5dc64a873d0acdace290f0211083c"

func init() {
	grammarruntime.RegisterEditorconfigSupport()
	grammarruntime.RegisterBlob("editorconfig", grammarblobs.Editorconfig)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("editorconfig.bin") }
