//go:build !grammar_subset || grammar_subset_move

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package move provides the standalone move grammar.
package move

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "5d5ce4c379d2bf38f1d9c3a4d6fcb3bd0b4bf708722b1ea454b80be21452bd53"

func init() {
	grammarruntime.RegisterMoveSupport()
	grammarruntime.RegisterBlob("move", grammarblobs.Move)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("move") }
