//go:build !grammar_subset || grammar_subset_cooklang

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cooklang provides the standalone cooklang grammar.
package cooklang

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2fd57f20461bcc0830fd14420cd06ad08750dd3cbbc440670e63056d59b3692a"

func init() {
	grammarruntime.RegisterCooklangSupport()
	grammarruntime.RegisterBlob("cooklang", grammarblobs.Cooklang)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cooklang") }
