//go:build !grammar_subset || grammar_subset_yuck

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package yuck provides the standalone yuck grammar.
package yuck

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "72fdb7bdfe65427a4c891777b8d6d89c578807a1719e0bbd17c4b1c2e98f357e"

func init() {
	grammarruntime.RegisterYuckSupport()
	grammarruntime.RegisterBlob("yuck", grammarblobs.Yuck)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("yuck.bin") }
