//go:build !grammar_subset || grammar_subset_d

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package d provides the standalone d grammar.
package d

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1bdab06c1772ec18a0bb4c87c8a3b1dccecddc8447b00571ea85c03486a3a2d8"

func init() { grammarruntime.RegisterDSupport(); grammarruntime.RegisterBlob("d", grammarblobs.D) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("d.bin") }
