//go:build !grammar_subset || grammar_subset_d

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package d provides the standalone d grammar.
package d

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1e2bf6c9d37193dad050a3e2f35d450973245dbee60550ef6cc24fca2b0e0016"

func init() { grammarruntime.RegisterDSupport(); grammarruntime.RegisterBlob("d", grammarblobs.D) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("d") }
