//go:build !grammar_subset || grammar_subset_org

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package org provides the standalone org grammar.
package org

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "74c3f35d34521aa56860eadc1fefe6d89ce321e9e3cf89a4c1e15b99651e190e"

func init() {
	grammarruntime.RegisterOrgSupport()
	grammarruntime.RegisterBlob("org", grammarblobs.Org)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("org.bin") }
