//go:build !grammar_subset || grammar_subset_org

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package org provides the standalone org grammar.
package org

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "67e67265d2b5a5531e9f984dbb220ab5322fd77501eaf616d18571a334f77dad"

func init() {
	grammarruntime.RegisterOrgSupport()
	grammarruntime.RegisterBlob("org", grammarblobs.Org)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("org.bin") }
