//go:build !grammar_subset || grammar_subset_org

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package org provides the standalone org grammar.
package org

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d267e28494f48f83dd64da4d6c0651b5648e4d86dce3a513872aeabc525cc4c2"

func init() {
	grammarruntime.RegisterOrgSupport()
	grammarruntime.RegisterBlob("org", grammarblobs.Org)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("org") }
