//go:build !grammar_subset || grammar_subset_jsonnet

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package jsonnet provides the standalone jsonnet grammar.
package jsonnet

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "bd17258dfc9a4cb24b153896391e4bb4634c2abb5b73eeab2aae5e92af92f326"

func init() {
	grammarruntime.RegisterJsonnetSupport()
	grammarruntime.RegisterBlob("jsonnet", grammarblobs.Jsonnet)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("jsonnet.bin") }
