//go:build !grammar_subset || grammar_subset_elixir

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package elixir provides the standalone elixir grammar.
package elixir

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ad2b6edb68e747161acb8383d37407e1821f89717ca7dbb97c20e83d5c1dc732"

func init() {
	grammarruntime.RegisterElixirSupport()
	grammarruntime.RegisterBlob("elixir", grammarblobs.Elixir)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("elixir.bin") }
