//go:build !grammar_subset || grammar_subset_elixir

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package elixir provides the standalone elixir grammar.
package elixir

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9889f5f6704ea87f357c8d65ef3194d88fb5865922b45767fe4df0f2eda7e3f0"

func init() {
	grammarruntime.RegisterElixirSupport()
	grammarruntime.RegisterBlob("elixir", grammarblobs.Elixir)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("elixir") }
