//go:build !grammar_subset || grammar_subset_liquid

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package liquid provides the standalone liquid grammar.
package liquid

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ed5a32cdd6c9e7a3cdf6ee940b7e7a805266582b8e8f77536f4966cf9e393c75"

func init() {
	grammarruntime.RegisterLiquidSupport()
	grammarruntime.RegisterBlob("liquid", grammarblobs.Liquid)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("liquid.bin") }
