//go:build !grammar_subset || grammar_subset_liquid

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package liquid provides the standalone liquid grammar.
package liquid

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9007c8806b1b71f9d73e731e33158b44558ebca7dec788cbc7932db5ea62a7f7"

func init() {
	grammarruntime.RegisterLiquidSupport()
	grammarruntime.RegisterBlob("liquid", grammarblobs.Liquid)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("liquid.bin") }
