//go:build !grammar_subset || grammar_subset_liquid

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package liquid provides the standalone liquid grammar.
package liquid

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1d214867fc2d1fa0db88e23c301e8b0353efb33fd3c98cc722be6493dbb41fdc"

func init() {
	grammarruntime.RegisterLiquidSupport()
	grammarruntime.RegisterBlob("liquid", grammarblobs.Liquid)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("liquid") }
