//go:build !grammar_subset || grammar_subset_hlsl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package hlsl provides the standalone hlsl grammar.
package hlsl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "28eaea578abbfb699f3ad829e7aff511007029a9b1a9ea6910f1a320af598a5f"

func init() {
	grammarruntime.RegisterHlslSupport()
	grammarruntime.RegisterBlob("hlsl", grammarblobs.Hlsl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("hlsl.bin") }
