//go:build !grammar_subset || grammar_subset_hlsl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package hlsl provides the standalone hlsl grammar.
package hlsl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "998c2cd319ff830a2cfc4c3f27a93873e5b6edc88754ca22b7d20aab60f6a6b0"

func init() {
	grammarruntime.RegisterHlslSupport()
	grammarruntime.RegisterBlob("hlsl", grammarblobs.Hlsl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("hlsl.bin") }
