//go:build !grammar_subset || grammar_subset_ruby

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ruby provides the standalone ruby grammar.
package ruby

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b5d22521822dce4f16d684ee70a49769e489dbd4c179ed6f091a854580b3d05b"

func init() {
	grammarruntime.RegisterRubySupport()
	grammarruntime.RegisterBlob("ruby", grammarblobs.Ruby)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ruby.bin") }
