//go:build !grammar_subset || grammar_subset_json

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package json provides the standalone json grammar.
package json

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ad656555b6909bc8efbf40eceb2ac98121f7abdf707c829c9dc03ebe6d83bfbf"

func init() { ; grammarruntime.RegisterBlob("json", grammarblobs.Json) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("json.bin") }
