//go:build !grammar_subset || grammar_subset_firrtl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package firrtl provides the standalone firrtl grammar.
package firrtl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "09528127a7fa1d301ffe99cadde04cc564f636b28a30dbddf253a225190d264b"

func init() {
	grammarruntime.RegisterFirrtlSupport()
	grammarruntime.RegisterBlob("firrtl", grammarblobs.Firrtl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("firrtl.bin") }
