//go:build !grammar_subset || grammar_subset_firrtl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package firrtl provides the standalone firrtl grammar.
package firrtl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "4873217e202fafd6d23e91fc677b008d9a984ef2363a86d6102fa7a55189e231"

func init() {
	grammarruntime.RegisterFirrtlSupport()
	grammarruntime.RegisterBlob("firrtl", grammarblobs.Firrtl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("firrtl.bin") }
