//go:build !grammar_subset || grammar_subset_kotlin

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package kotlin provides the standalone kotlin grammar.
package kotlin

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "643a3e6b60d07846dd972849b612159ff9bf09734b09fb00013229c8593a8c78"

func init() {
	grammarruntime.RegisterKotlinSupport()
	grammarruntime.RegisterBlob("kotlin", grammarblobs.Kotlin)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("kotlin.bin") }
