//go:build !grammar_subset || grammar_subset_regex

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package regex provides the standalone regex grammar.
package regex

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "fb4c90af621a6a5303260f34722ffb26c72e1d1433b9a11387b6ecbb247ca6a1"

func init() { ; grammarruntime.RegisterBlob("regex", grammarblobs.Regex) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("regex") }
