//go:build !grammar_subset || grammar_subset_mojo

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package mojo provides the standalone mojo grammar.
package mojo

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "6216b2c1aecc722ea11a20ae5e936581546824310e0eeaa12ae707d6ca762f5c"

func init() {
	grammarruntime.RegisterMojoSupport()
	grammarruntime.RegisterBlob("mojo", grammarblobs.Mojo)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("mojo.bin") }
