//go:build !grammar_subset || grammar_subset_mojo

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package mojo provides the standalone mojo grammar.
package mojo

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9db74c4b835d992c97adc0ad686767e470b80e912f82e1eb2603e4525377db38"

func init() {
	grammarruntime.RegisterMojoSupport()
	grammarruntime.RegisterBlob("mojo", grammarblobs.Mojo)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("mojo") }
