//go:build !grammar_subset || grammar_subset_bicep

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package bicep provides the standalone bicep grammar.
package bicep

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "242d4d5acc1238f53aadeeefe9e4618f999be5196607744f257e5e189f96d728"

func init() {
	grammarruntime.RegisterBicepSupport()
	grammarruntime.RegisterBlob("bicep", grammarblobs.Bicep)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("bicep") }
