//go:build !grammar_subset || grammar_subset_solidity

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package solidity provides the standalone solidity grammar.
package solidity

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3ad715d0697c13301e6f12f73ac42db4e540210cc6cf8115c6ae934e5e21dda1"

func init() { ; grammarruntime.RegisterBlob("solidity", grammarblobs.Solidity) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("solidity.bin") }
