//go:build !grammar_subset || grammar_subset_dtd

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package dtd provides the standalone dtd grammar.
package dtd

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b5b8bea4e06199e1f64c4600287aabe9dc583178ce3ae0d7f138eab8630ee57d"

func init() {
	grammarruntime.RegisterDtdSupport()
	grammarruntime.RegisterBlob("dtd", grammarblobs.Dtd)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("dtd") }
