//go:build !grammar_subset || grammar_subset_beancount

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package beancount provides the standalone beancount grammar.
package beancount

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "de280116ddd396d3499fe9089920f4a6167e2c6dea95531f097186bf242ff75e"

func init() {
	grammarruntime.RegisterBeancountSupport()
	grammarruntime.RegisterBlob("beancount", grammarblobs.Beancount)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("beancount.bin") }
