package gotreesitter_test

import "testing"

// Generated from grammars/runtime/builtin_scanners_gen.go's RegisterXxxSupport
// roster (119 entries as of hardening/fuzz-blob-safety). Each function is a
// one-line call into fuzzScannerGrammar (fuzz_scanner_grammars_test.go); see
// that file for the shared harness, budgets, and seed corpus.

func FuzzScanner_Agda(f *testing.F)            { fuzzScannerGrammar(f, "agda") }
func FuzzScanner_Angular(f *testing.F)         { fuzzScannerGrammar(f, "angular") }
func FuzzScanner_Arduino(f *testing.F)         { fuzzScannerGrammar(f, "arduino") }
func FuzzScanner_Astro(f *testing.F)           { fuzzScannerGrammar(f, "astro") }
func FuzzScanner_Awk(f *testing.F)             { fuzzScannerGrammar(f, "awk") }
func FuzzScanner_Bash(f *testing.F)            { fuzzScannerGrammar(f, "bash") }
func FuzzScanner_Beancount(f *testing.F)       { fuzzScannerGrammar(f, "beancount") }
func FuzzScanner_Bicep(f *testing.F)           { fuzzScannerGrammar(f, "bicep") }
func FuzzScanner_Bitbake(f *testing.F)         { fuzzScannerGrammar(f, "bitbake") }
func FuzzScanner_Blade(f *testing.F)           { fuzzScannerGrammar(f, "blade") }
func FuzzScanner_C_sharp(f *testing.F)         { fuzzScannerGrammar(f, "c_sharp") }
func FuzzScanner_Caddy(f *testing.F)           { fuzzScannerGrammar(f, "caddy") }
func FuzzScanner_Cairo(f *testing.F)           { fuzzScannerGrammar(f, "cairo") }
func FuzzScanner_Cmake(f *testing.F)           { fuzzScannerGrammar(f, "cmake") }
func FuzzScanner_Cobol(f *testing.F)           { fuzzScannerGrammar(f, "cobol") }
func FuzzScanner_Comment(f *testing.F)         { fuzzScannerGrammar(f, "comment") }
func FuzzScanner_Cooklang(f *testing.F)        { fuzzScannerGrammar(f, "cooklang") }
func FuzzScanner_Cpp(f *testing.F)             { fuzzScannerGrammar(f, "cpp") }
func FuzzScanner_Crystal(f *testing.F)         { fuzzScannerGrammar(f, "crystal") }
func FuzzScanner_Css(f *testing.F)             { fuzzScannerGrammar(f, "css") }
func FuzzScanner_Cuda(f *testing.F)            { fuzzScannerGrammar(f, "cuda") }
func FuzzScanner_Cue(f *testing.F)             { fuzzScannerGrammar(f, "cue") }
func FuzzScanner_D(f *testing.F)               { fuzzScannerGrammar(f, "d") }
func FuzzScanner_Dart(f *testing.F)            { fuzzScannerGrammar(f, "dart") }
func FuzzScanner_Dhall(f *testing.F)           { fuzzScannerGrammar(f, "dhall") }
func FuzzScanner_Disassembly(f *testing.F)     { fuzzScannerGrammar(f, "disassembly") }
func FuzzScanner_Djot(f *testing.F)            { fuzzScannerGrammar(f, "djot") }
func FuzzScanner_Dockerfile(f *testing.F)      { fuzzScannerGrammar(f, "dockerfile") }
func FuzzScanner_Doxygen(f *testing.F)         { fuzzScannerGrammar(f, "doxygen") }
func FuzzScanner_Dtd(f *testing.F)             { fuzzScannerGrammar(f, "dtd") }
func FuzzScanner_Earthfile(f *testing.F)       { fuzzScannerGrammar(f, "earthfile") }
func FuzzScanner_Editorconfig(f *testing.F)    { fuzzScannerGrammar(f, "editorconfig") }
func FuzzScanner_Elixir(f *testing.F)          { fuzzScannerGrammar(f, "elixir") }
func FuzzScanner_Elm(f *testing.F)             { fuzzScannerGrammar(f, "elm") }
func FuzzScanner_Erlang(f *testing.F)          { fuzzScannerGrammar(f, "erlang") }
func FuzzScanner_Fennel(f *testing.F)          { fuzzScannerGrammar(f, "fennel") }
func FuzzScanner_Firrtl(f *testing.F)          { fuzzScannerGrammar(f, "firrtl") }
func FuzzScanner_Fish(f *testing.F)            { fuzzScannerGrammar(f, "fish") }
func FuzzScanner_Foam(f *testing.F)            { fuzzScannerGrammar(f, "foam") }
func FuzzScanner_Fortran(f *testing.F)         { fuzzScannerGrammar(f, "fortran") }
func FuzzScanner_Fsharp(f *testing.F)          { fuzzScannerGrammar(f, "fsharp") }
func FuzzScanner_Gdscript(f *testing.F)        { fuzzScannerGrammar(f, "gdscript") }
func FuzzScanner_Gitcommit(f *testing.F)       { fuzzScannerGrammar(f, "gitcommit") }
func FuzzScanner_Gleam(f *testing.F)           { fuzzScannerGrammar(f, "gleam") }
func FuzzScanner_Gn(f *testing.F)              { fuzzScannerGrammar(f, "gn") }
func FuzzScanner_Go(f *testing.F)              { fuzzScannerGrammar(f, "go") }
func FuzzScanner_Godot_resource(f *testing.F)  { fuzzScannerGrammar(f, "godot_resource") }
func FuzzScanner_Hack(f *testing.F)            { fuzzScannerGrammar(f, "hack") }
func FuzzScanner_Haskell(f *testing.F)         { fuzzScannerGrammar(f, "haskell") }
func FuzzScanner_Haxe(f *testing.F)            { fuzzScannerGrammar(f, "haxe") }
func FuzzScanner_Hcl(f *testing.F)             { fuzzScannerGrammar(f, "hcl") }
func FuzzScanner_Hlsl(f *testing.F)            { fuzzScannerGrammar(f, "hlsl") }
func FuzzScanner_Html(f *testing.F)            { fuzzScannerGrammar(f, "html") }
func FuzzScanner_Janet(f *testing.F)           { fuzzScannerGrammar(f, "janet") }
func FuzzScanner_Javascript(f *testing.F)      { fuzzScannerGrammar(f, "javascript") }
func FuzzScanner_Jsdoc(f *testing.F)           { fuzzScannerGrammar(f, "jsdoc") }
func FuzzScanner_Jsonnet(f *testing.F)         { fuzzScannerGrammar(f, "jsonnet") }
func FuzzScanner_Julia(f *testing.F)           { fuzzScannerGrammar(f, "julia") }
func FuzzScanner_Just(f *testing.F)            { fuzzScannerGrammar(f, "just") }
func FuzzScanner_Kconfig(f *testing.F)         { fuzzScannerGrammar(f, "kconfig") }
func FuzzScanner_Kdl(f *testing.F)             { fuzzScannerGrammar(f, "kdl") }
func FuzzScanner_Kotlin(f *testing.F)          { fuzzScannerGrammar(f, "kotlin") }
func FuzzScanner_Less(f *testing.F)            { fuzzScannerGrammar(f, "less") }
func FuzzScanner_Liquid(f *testing.F)          { fuzzScannerGrammar(f, "liquid") }
func FuzzScanner_Lua(f *testing.F)             { fuzzScannerGrammar(f, "lua") }
func FuzzScanner_Luau(f *testing.F)            { fuzzScannerGrammar(f, "luau") }
func FuzzScanner_Markdown(f *testing.F)        { fuzzScannerGrammar(f, "markdown") }
func FuzzScanner_Markdown_inline(f *testing.F) { fuzzScannerGrammar(f, "markdown_inline") }
func FuzzScanner_Matlab(f *testing.F)          { fuzzScannerGrammar(f, "matlab") }
func FuzzScanner_Mojo(f *testing.F)            { fuzzScannerGrammar(f, "mojo") }
func FuzzScanner_Move(f *testing.F)            { fuzzScannerGrammar(f, "move") }
func FuzzScanner_Nginx(f *testing.F)           { fuzzScannerGrammar(f, "nginx") }
func FuzzScanner_Nickel(f *testing.F)          { fuzzScannerGrammar(f, "nickel") }
func FuzzScanner_Nim(f *testing.F)             { fuzzScannerGrammar(f, "nim") }
func FuzzScanner_Nix(f *testing.F)             { fuzzScannerGrammar(f, "nix") }
func FuzzScanner_Norg(f *testing.F)            { fuzzScannerGrammar(f, "norg") }
func FuzzScanner_Nushell(f *testing.F)         { fuzzScannerGrammar(f, "nushell") }
func FuzzScanner_Ocaml(f *testing.F)           { fuzzScannerGrammar(f, "ocaml") }
func FuzzScanner_Odin(f *testing.F)            { fuzzScannerGrammar(f, "odin") }
func FuzzScanner_Org(f *testing.F)             { fuzzScannerGrammar(f, "org") }
func FuzzScanner_Perl(f *testing.F)            { fuzzScannerGrammar(f, "perl") }
func FuzzScanner_Php(f *testing.F)             { fuzzScannerGrammar(f, "php") }
func FuzzScanner_Pkl(f *testing.F)             { fuzzScannerGrammar(f, "pkl") }
func FuzzScanner_Powershell(f *testing.F)      { fuzzScannerGrammar(f, "powershell") }
func FuzzScanner_Properties(f *testing.F)      { fuzzScannerGrammar(f, "properties") }
func FuzzScanner_Pug(f *testing.F)             { fuzzScannerGrammar(f, "pug") }
func FuzzScanner_Purescript(f *testing.F)      { fuzzScannerGrammar(f, "purescript") }
func FuzzScanner_Python(f *testing.F)          { fuzzScannerGrammar(f, "python") }
func FuzzScanner_R(f *testing.F)               { fuzzScannerGrammar(f, "r") }
func FuzzScanner_Racket(f *testing.F)          { fuzzScannerGrammar(f, "racket") }
func FuzzScanner_Rescript(f *testing.F)        { fuzzScannerGrammar(f, "rescript") }
func FuzzScanner_Ron(f *testing.F)             { fuzzScannerGrammar(f, "ron") }
func FuzzScanner_Rst(f *testing.F)             { fuzzScannerGrammar(f, "rst") }
func FuzzScanner_Ruby(f *testing.F)            { fuzzScannerGrammar(f, "ruby") }
func FuzzScanner_Rust(f *testing.F)            { fuzzScannerGrammar(f, "rust") }
func FuzzScanner_Scala(f *testing.F)           { fuzzScannerGrammar(f, "scala") }
func FuzzScanner_Scss(f *testing.F)            { fuzzScannerGrammar(f, "scss") }
func FuzzScanner_Sql(f *testing.F)             { fuzzScannerGrammar(f, "sql") }
func FuzzScanner_Squirrel(f *testing.F)        { fuzzScannerGrammar(f, "squirrel") }
func FuzzScanner_Starlark(f *testing.F)        { fuzzScannerGrammar(f, "starlark") }
func FuzzScanner_Svelte(f *testing.F)          { fuzzScannerGrammar(f, "svelte") }
func FuzzScanner_Swift(f *testing.F)           { fuzzScannerGrammar(f, "swift") }
func FuzzScanner_Tablegen(f *testing.F)        { fuzzScannerGrammar(f, "tablegen") }
func FuzzScanner_Tcl(f *testing.F)             { fuzzScannerGrammar(f, "tcl") }
func FuzzScanner_Teal(f *testing.F)            { fuzzScannerGrammar(f, "teal") }
func FuzzScanner_Templ(f *testing.F)           { fuzzScannerGrammar(f, "templ") }
func FuzzScanner_Tlaplus(f *testing.F)         { fuzzScannerGrammar(f, "tlaplus") }
func FuzzScanner_Toml(f *testing.F)            { fuzzScannerGrammar(f, "toml") }
func FuzzScanner_Tsx(f *testing.F)             { fuzzScannerGrammar(f, "tsx") }
func FuzzScanner_Typescript(f *testing.F)      { fuzzScannerGrammar(f, "typescript") }
func FuzzScanner_Typst(f *testing.F)           { fuzzScannerGrammar(f, "typst") }
func FuzzScanner_Uxntal(f *testing.F)          { fuzzScannerGrammar(f, "uxntal") }
func FuzzScanner_Vhdl(f *testing.F)            { fuzzScannerGrammar(f, "vhdl") }
func FuzzScanner_Vue(f *testing.F)             { fuzzScannerGrammar(f, "vue") }
func FuzzScanner_Wgsl(f *testing.F)            { fuzzScannerGrammar(f, "wgsl") }
func FuzzScanner_Wolfram(f *testing.F)         { fuzzScannerGrammar(f, "wolfram") }
func FuzzScanner_Xml(f *testing.F)             { fuzzScannerGrammar(f, "xml") }
func FuzzScanner_Yaml(f *testing.F)            { fuzzScannerGrammar(f, "yaml") }
func FuzzScanner_Yuck(f *testing.F)            { fuzzScannerGrammar(f, "yuck") }
