//go:build !grammar_subset || grammar_subset_csv

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package csv provides the standalone csv grammar.
package csv

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1807b930c4e4116baa77dd1631d1879befc87b8421020dd4d11ba18ac00099f5"

func init() { ; grammarruntime.RegisterBlob("csv", grammarblobs.Csv) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("csv") }
