//go:build !grammar_subset || grammar_subset_csv

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package csv provides the standalone csv grammar.
package csv

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8ec42b654bc16f421ac18c9701b2a96dab5207d761c5aceeb4ece0c7e79e28ef"

func init() { ; grammarruntime.RegisterBlob("csv", grammarblobs.Csv) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("csv.bin") }
