//go:build !grammar_subset || grammar_subset_r

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package r provides the standalone r grammar.
package r

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b09226c9eae0afc795d22e3dbed168118554d05b7ab80113bf06bb4315b90c4d"

func init() { grammarruntime.RegisterRSupport(); grammarruntime.RegisterBlob("r", grammarblobs.R) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("r") }
