//go:build !grammar_subset || grammar_subset_r

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package r provides the standalone r grammar.
package r

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b954781f75b780d26a01f009aa12e47cbfd243dea0c65784c9b3ec21cb80cf50"

func init() { grammarruntime.RegisterRSupport(); grammarruntime.RegisterBlob("r", grammarblobs.R) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("r.bin") }
