//go:build !grammar_subset || grammar_subset_rust

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package rust provides the standalone rust grammar.
package rust

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "271f0677bba8bad352849d68b10bd250d72bbfc0350833b91c6956f811717b6c"

func init() {
	grammarruntime.RegisterRustSupport()
	grammarruntime.RegisterBlob("rust", grammarblobs.Rust)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("rust.bin") }
