//go:build !grammar_subset || grammar_subset_caddy

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package caddy provides the standalone caddy grammar.
package caddy

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "94b81aa106461eaa9ef1ed8b3d25abdae36ac10b7b659ed3ec9bc21634c277db"

func init() {
	grammarruntime.RegisterCaddySupport()
	grammarruntime.RegisterBlob("caddy", grammarblobs.Caddy)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("caddy.bin") }
