//go:build !grammar_subset || grammar_subset_eex

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package eex provides the standalone eex grammar.
package eex

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "13ad5adb07d9519b0335093e4b1689be59919ff7d12be6b2e9a7db5646f80f5c"

func init() { ; grammarruntime.RegisterBlob("eex", grammarblobs.Eex) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("eex") }
