//go:build !grammar_subset || grammar_subset_pug

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package pug provides the standalone pug grammar.
package pug

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "189dc104b4be349da913a0a5887a9d25c3af95792bed4de4e2f605550f67f5c5"

func init() {
	grammarruntime.RegisterPugSupport()
	grammarruntime.RegisterBlob("pug", grammarblobs.Pug)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("pug") }
