//go:build !grammar_subset || grammar_subset_pug

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package pug provides the standalone pug grammar.
package pug

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2ea40aa6009366aa71dec348e20f94f760576b69d1fa824531ad28ce7ed15441"

func init() {
	grammarruntime.RegisterPugSupport()
	grammarruntime.RegisterBlob("pug", grammarblobs.Pug)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("pug.bin") }
