//go:build !grammar_subset || grammar_subset_brightscript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package brightscript provides the standalone brightscript grammar.
package brightscript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "52e12712ce9da627c198613023e56d3d508d2b73366bbe8f82cb54a4079286c3"

func init() { ; grammarruntime.RegisterBlob("brightscript", grammarblobs.Brightscript) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("brightscript") }
