//go:build !grammar_subset || grammar_subset_cuda

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cuda provides the standalone cuda grammar.
package cuda

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "be805d7ba5a305333f6492dba3a656e9d413915e9c3dfa2eb08d001fcfa6a7b9"

func init() {
	grammarruntime.RegisterCudaSupport()
	grammarruntime.RegisterBlob("cuda", grammarblobs.Cuda)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cuda.bin") }
