//go:build !grammar_subset || grammar_subset_cuda

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cuda provides the standalone cuda grammar.
package cuda

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "0bac15a5984043d091e6c49d48ef3d6b3189db5e85a1c62f26aebf635c41b056"

func init() {
	grammarruntime.RegisterCudaSupport()
	grammarruntime.RegisterBlob("cuda", grammarblobs.Cuda)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cuda.bin") }
