//go:build !grammar_subset || grammar_subset_elisp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package elisp provides the standalone elisp grammar.
package elisp

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "034f9be93094b0b57d2a3f2295cd843b46d3ac8fd6ea8072056bab562cd75c59"

func init() { ; grammarruntime.RegisterBlob("elisp", grammarblobs.Elisp) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("elisp") }
