//go:build !grammar_subset || grammar_subset_clojure

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package clojure provides the standalone clojure grammar.
package clojure

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9e97c4185fc120df97c8155070693c05440eb76d202128ba3d07fbdcc11f18b1"

func init() { ; grammarruntime.RegisterBlob("clojure", grammarblobs.Clojure) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("clojure") }
