//go:build !grammar_subset || grammar_subset_haxe

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package haxe provides the standalone haxe grammar.
package haxe

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "eb39b273148a394f792b322cd30b5483fd6f8ca915b7e15835de4d6482b5a4a7"

func init() {
	grammarruntime.RegisterHaxeSupport()
	grammarruntime.RegisterBlob("haxe", grammarblobs.Haxe)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("haxe") }
