//go:build !grammar_subset || grammar_subset_haxe

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package haxe provides the standalone haxe grammar.
package haxe

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "0c6700b392306bd99cdfdafff1896c28dfea08089d962ce19bac66511b032eda"

func init() {
	grammarruntime.RegisterHaxeSupport()
	grammarruntime.RegisterBlob("haxe", grammarblobs.Haxe)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("haxe.bin") }
