//go:build !grammar_subset || grammar_subset_json5

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package json5 provides the standalone json5 grammar.
package json5

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "963edcddf71f37e7dfb9916ada556c594053722bcf7786b9c3cde84b74d40069"

func init() { ; grammarruntime.RegisterBlob("json5", grammarblobs.Json5) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("json5") }
