//go:build !grammar_subset || grammar_subset_vhdl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package vhdl provides the standalone vhdl grammar.
package vhdl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d694e880d2fc2693ee79bbc1de6714123f9e4ba542824100413cf741ab1815e7"

func init() {
	grammarruntime.RegisterVhdlSupport()
	grammarruntime.RegisterBlob("vhdl", grammarblobs.Vhdl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("vhdl.bin") }
