//go:build !grammar_subset || grammar_subset_gitattributes

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package gitattributes provides the standalone gitattributes grammar.
package gitattributes

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "565c2d96504e37a6915e5188ca3ec2666ed9723c63f0007a8cdf71496a598131"

func init() { ; grammarruntime.RegisterBlob("gitattributes", grammarblobs.Gitattributes) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("gitattributes.bin") }
