//go:build !grammar_subset || grammar_subset_gitattributes

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package gitattributes provides the standalone gitattributes grammar.
package gitattributes

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2a8d50b459ba0ba3c1ff5efed4db2d90106af0a289c0f84a69729bc7e61db5d5"

func init() { ; grammarruntime.RegisterBlob("gitattributes", grammarblobs.Gitattributes) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("gitattributes.bin") }
