//go:build !grammar_subset || grammar_subset_toml

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package toml provides the standalone toml grammar.
package toml

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "11063816fe4e81ee20cc3d60c4f2e8867dd4971065ecf3b4cf490467ca9b99bc"

func init() {
	grammarruntime.RegisterTomlSupport()
	grammarruntime.RegisterBlob("toml", grammarblobs.Toml)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("toml.bin") }
