//go:build !grammar_subset || grammar_subset_circom

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package circom provides the standalone circom grammar.
package circom

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "4ab840c83d800f1ae0638e37aa22d70997fed9b2a47b633ff676e9900d30356f"

func init() { ; grammarruntime.RegisterBlob("circom", grammarblobs.Circom) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("circom.bin") }
