//go:build !grammar_subset || grammar_subset_jinja2

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package jinja2 provides the standalone jinja2 grammar.
package jinja2

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d5861c5c92faebb418a5b56dc0220ae13bcf998bd11515f0e4feaf28a2123ffb"

func init() { ; grammarruntime.RegisterBlob("jinja2", grammarblobs.Jinja2) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("jinja2") }
