//go:build !grammar_subset || grammar_subset_tcl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package tcl provides the standalone tcl grammar.
package tcl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "4c331e38860001c18b737f6be508f4b09f230c4b9ff95f4b4d12bdb00c176ad7"

func init() {
	grammarruntime.RegisterTclSupport()
	grammarruntime.RegisterBlob("tcl", grammarblobs.Tcl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("tcl.bin") }
