// Code generated by compat/smacker grammar mapping. DO NOT EDIT.
package kotlin

import (
	sitter "github.com/odvcencio/gotreesitter/compat/smacker"
	"github.com/odvcencio/gotreesitter/grammars"
)

// GetLanguage returns the KotlinLanguage grammar handle, mirroring the smacker
// per-grammar package of the same import path.
func GetLanguage() *sitter.Language { return grammars.KotlinLanguage() }
