//go:build !grammar_subset || grammar_subset_v

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package v provides the standalone v grammar.
package v

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "bd155fc131bd0cdba6ecfdc758e0145c0e4dd80fe5d792562b1351953b63b6a3"

func init() { ; grammarruntime.RegisterBlob("v", grammarblobs.V) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("v.bin") }
