//go:build !grammar_subset || grammar_subset_nim

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package nim provides the standalone nim grammar.
package nim

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "5ab27abdf0108d67f2a92d49db4b6b20eae975805161b205aeb371a25972553b"

func init() {
	grammarruntime.RegisterNimSupport()
	grammarruntime.RegisterBlob("nim", grammarblobs.Nim)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("nim.bin") }
