//go:build !grammar_subset || grammar_subset_nim

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package nim provides the standalone nim grammar.
package nim

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ab35a5bf26bf423e17c8743fd6b68cfe7b899dda4a0f99c522208a85d7bd081f"

func init() {
	grammarruntime.RegisterNimSupport()
	grammarruntime.RegisterBlob("nim", grammarblobs.Nim)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("nim") }
