//go:build !grammar_subset || grammar_subset_bash

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package bash provides the standalone bash grammar.
package bash

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a3e898c88f6ad918d4d619dff2a4e74d613bda93c90e4a3f9fb7587c1952f3fb"

func init() {
	grammarruntime.RegisterBashSupport()
	grammarruntime.RegisterBlob("bash", grammarblobs.Bash)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("bash") }
