//go:build !grammar_subset || grammar_subset_bash

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package bash provides the standalone bash grammar.
package bash

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a9ee051db3a7997116516cf2649f9afb187271bf278929b199cded93f0483aa0"

func init() {
	grammarruntime.RegisterBashSupport()
	grammarruntime.RegisterBlob("bash", grammarblobs.Bash)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("bash.bin") }
