//go:build !grammar_subset || grammar_subset_fsharp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package fsharp provides the standalone fsharp grammar.
package fsharp

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "5d7431b2bdd3af22d339ad36e0c1a75287faea5589f73d01c277d6b54acd6d13"

func init() {
	grammarruntime.RegisterFsharpSupport()
	grammarruntime.RegisterBlob("fsharp", grammarblobs.Fsharp)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("fsharp.bin") }
