//go:build !grammar_subset || grammar_subset_fsharp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package fsharp provides the standalone fsharp grammar.
package fsharp

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "409f32a1a287c9f2a385dc96bea03ed8b700bc9bfe92c50f91eed538519475ae"

func init() {
	grammarruntime.RegisterFsharpSupport()
	grammarruntime.RegisterBlob("fsharp", grammarblobs.Fsharp)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("fsharp.bin") }
