//go:build !grammar_subset || grammar_subset_tsx

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package tsx provides the standalone tsx grammar.
package tsx

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "256ffdaa188095e38dcec6e135457aa3f72a3dcd35ec56814d6ae108b9500af2"

func init() {
	grammarruntime.RegisterTsxSupport()
	grammarruntime.RegisterBlob("tsx", grammarblobs.Tsx)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("tsx.bin") }
