//go:build !grammar_subset || grammar_subset_tsx

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package tsx provides the standalone tsx grammar.
package tsx

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "dbccff1bdab6c8cab89d930601893b5c2fbadc9a1808e8b8a0865f63faa7cbbd"

func init() {
	grammarruntime.RegisterTsxSupport()
	grammarruntime.RegisterBlob("tsx", grammarblobs.Tsx)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("tsx.bin") }
