//go:build !grammar_subset || grammar_subset_earthfile

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package earthfile provides the standalone earthfile grammar.
package earthfile

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "5eb40a8cd7b7af42523ae1a7a882b1e5f5d74c0971513716a9becc4cc3bcfe2a"

func init() {
	grammarruntime.RegisterEarthfileSupport()
	grammarruntime.RegisterBlob("earthfile", grammarblobs.Earthfile)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("earthfile.bin") }
