//go:build !grammar_subset || grammar_subset_earthfile

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package earthfile provides the standalone earthfile grammar.
package earthfile

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3bf1f73212017864511288f5141fea34ab54a51f9542ac5d3a0bdee8b2388c94"

func init() {
	grammarruntime.RegisterEarthfileSupport()
	grammarruntime.RegisterBlob("earthfile", grammarblobs.Earthfile)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("earthfile") }
