//go:build !grammar_subset || grammar_subset_djot

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package djot provides the standalone djot grammar.
package djot

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3f4eea79bc424a6a9bdc85d7118865e63170d7768611de9ada17dc7fa10809a0"

func init() {
	grammarruntime.RegisterDjotSupport()
	grammarruntime.RegisterBlob("djot", grammarblobs.Djot)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("djot") }
