//go:build !grammar_subset || grammar_subset_ocaml

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ocaml provides the standalone ocaml grammar.
package ocaml

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "85fc5e7ac0ff1afc791e2c4b9a08153bd5265ee435e582e9014bf35f8895296d"

func init() {
	grammarruntime.RegisterOcamlSupport()
	grammarruntime.RegisterBlob("ocaml", grammarblobs.Ocaml)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ocaml.bin") }
