//go:build !grammar_subset || grammar_subset_ocaml

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ocaml provides the standalone ocaml grammar.
package ocaml

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b4419fe4c29bb56001426c17c8775133b553ca9db62e4d101c16ca61f8a157ca"

func init() {
	grammarruntime.RegisterOcamlSupport()
	grammarruntime.RegisterBlob("ocaml", grammarblobs.Ocaml)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ocaml.bin") }
