//go:build !grammar_subset || grammar_subset_authzed

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/odvcencio/gotreesitter"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

type AuthzedTokenSource = grammarruntime.AuthzedTokenSource

func NewAuthzedTokenSource(src []byte, lang *gotreesitter.Language) (*AuthzedTokenSource, error) {
	return grammarruntime.NewAuthzedTokenSource(src, lang)
}
func NewAuthzedTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewAuthzedTokenSourceOrEOF(src, lang)
}
