//go:build !grammar_subset || grammar_subset_c || grammar_subset_cpp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/odvcencio/gotreesitter"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

type CTokenSource = grammarruntime.CTokenSource

func NewCTokenSource(src []byte, lang *gotreesitter.Language) (*CTokenSource, error) {
	return grammarruntime.NewCTokenSource(src, lang)
}
func NewCTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewCTokenSourceOrEOF(src, lang)
}
