//go:build !grammar_subset || grammar_subset_djot

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

type DjotExternalScanner = grammarruntime.DjotExternalScanner
