//go:build !grammar_subset || grammar_subset_go

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/odvcencio/gotreesitter"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

type GoTokenSource = grammarruntime.GoTokenSource

func NewGoTokenSource(src []byte, lang *gotreesitter.Language) (*GoTokenSource, error) {
	return grammarruntime.NewGoTokenSource(src, lang)
}
func NewGoTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewGoTokenSourceOrEOF(src, lang)
}
