//go:build !grammar_subset || grammar_subset_html

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/odvcencio/gotreesitter"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

type HTMLTokenSource = grammarruntime.HTMLTokenSource

func NewHTMLTokenSource(src []byte, lang *gotreesitter.Language) (*HTMLTokenSource, error) {
	return grammarruntime.NewHTMLTokenSource(src, lang)
}
func NewHTMLTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewHTMLTokenSourceOrEOF(src, lang)
}
