//go:build !grammar_subset || grammar_subset_java

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/odvcencio/gotreesitter"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

type JavaTokenSource = grammarruntime.JavaTokenSource

func NewJavaTokenSource(src []byte, lang *gotreesitter.Language) (*JavaTokenSource, error) {
	return grammarruntime.NewJavaTokenSource(src, lang)
}
func NewJavaTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewJavaTokenSourceOrEOF(src, lang)
}
