// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "plsql",
		Extensions:     []string{".spc", ".prc", ".fnc", ".bdy", ".sql"},
		Language:       PlsqlLanguage,
		HighlightQuery: plsqlHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("plsql"),
	})
}

const plsqlHighlightQuery = ""
