//go:build !grammar_subset || grammar_subset_powershell

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

type PowershellExternalScanner = grammarruntime.PowershellExternalScanner
