//go:build !grammar_subset || grammar_subset_properties

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

type PropertiesExternalScanner = grammarruntime.PropertiesExternalScanner
