//go:build grammar_subset && grammar_subset_angular

package grammars

func init() {
	Register(LangEntry{
		Name:           "angular",
		Language:       AngularLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; inherits: html\n\n(identifier) @variable\n\n(style_unit) @variable\n\n(pipe_operator) @operator\n\n(string) @string\n\n(number) @number\n\n(pipe_call\n  name: (identifier) @function)\n\n(pipe_call\n  arguments: (pipe_arguments\n    (identifier) @variable.parameter))\n\n(structural_directive\n  \"*\" @keyword\n  (identifier) @keyword)\n\n(attribute\n  (attribute_name) @variable.member\n  (#lua-match? @variable.member \"#.*\"))\n\n(binding_name\n  (identifier) @keyword)\n\n(class_binding\n  [\n    (identifier)\n    (class_name)\n  ] @keyword)\n\n(event_binding\n  (binding_name\n    (identifier) @keyword))\n\n(event_binding\n  \"\\\"\" @punctuation.delimiter)\n\n(property_binding\n  [\n   \"\\\"\"\n   \"\\\"\\\"\"\n  ] @punctuation.delimiter)\n\n(structural_assignment\n  operator: (identifier) @keyword)\n\n(member_expression\n  property: (identifier) @property)\n\n(call_expression\n  function: (identifier) @function)\n\n(call_expression\n  function: ((identifier) @function.builtin\n    (#eq? @function.builtin \"$any\")))\n\n(pair\n  key: ((identifier) @variable.builtin\n    (#eq? @variable.builtin \"$implicit\")))\n\n[\n  (control_keyword)\n  (special_keyword)\n] @keyword\n\n((control_keyword) @keyword.repeat\n  (#any-of? @keyword.repeat \"for\" \"empty\"))\n\n((control_keyword) @keyword.conditional\n  (#any-of? @keyword.conditional \"if\" \"else\" \"switch\" \"case\" \"default\"))\n\n((control_keyword) @keyword.coroutine\n  (#any-of? @keyword.coroutine \"defer\" \"placeholder\" \"loading\"))\n\n((control_keyword) @keyword.exception\n  (#eq? @keyword.exception \"error\"))\n\n((identifier) @boolean\n  (#any-of? @boolean \"true\" \"false\"))\n\n((identifier) @variable.builtin\n  (#any-of? @variable.builtin \"this\" \"$event\"))\n\n((identifier) @constant.builtin\n  (#eq? @constant.builtin \"null\"))\n\n[\n  (ternary_operator)\n  (conditional_operator)\n] @keyword.conditional.ternary\n\n[\n  \"(\"\n  \")\"\n  \"[\"\n  \"]\"\n  \"{\"\n  \"}\"\n  \"@\"\n] @punctuation.bracket\n\n(two_way_binding\n  [\n    \"[(\"\n    \")]\"\n  ] @punctuation.bracket)\n\n[\n  \"{{\"\n  \"}}\"\n] @punctuation.special\n\n(template_substitution\n  [\n    \"${\"\n    \"}\"\n  ] @punctuation.special)\n\n(template_chars) @string\n\n[\n  \";\"\n  \".\"\n  \",\"\n  \"?.\"\n  \"!.\"\n] @punctuation.delimiter\n\n(nullish_coalescing_expression\n  (coalescing_operator) @operator)\n\n(concatenation_expression\n  \"+\" @operator)\n\n(icu_clause) @keyword.operator\n\n(icu_category) @keyword.conditional\n\n(binary_expression\n  [\n    \"-\"\n    \"&&\"\n    \"+\"\n    \"<\"\n    \"<=\"\n    \"=\"\n    \"==\"\n    \"===\"\n    \"!=\"\n    \"!==\"\n    \">\"\n    \">=\"\n    \"*\"\n    \"/\"\n    \"||\"\n    \"%\"\n  ] @operator)\n\n(arrow_function\n  \"=>\" @operator)\n\n(object\n  (spread\n    \"...\" @operator))\n\n(array\n  (spread\n    \"...\" @operator))\n\n(arguments\n  (spread\n    \"...\" @operator))\n",
	})
}
