//go:build grammar_subset && grammar_subset_markdown_inline

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"

func init() { grammarruntime.RegisterMarkdown_inlineSupport() }
