//go:build grammar_subset && grammar_subset_r

package grammars

func init() {
	Register(LangEntry{
		Name:           "r",
		Extensions:     []string{".r", ".R"},
		Language:       RLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; highlights.scm\n\n; Literals\n\n(integer) @number\n(float) @number\n(complex) @number\n\n(string) @string\n(string (string_content (escape_sequence) @string.escape))\n\n; Comments\n\n(comment) @comment\n\n; Operators\n\n[\n  \"?\" \":=\" \"=\" \"<-\" \"<<-\" \"->\" \"->>\"\n  \"~\" \"|>\" \"||\" \"|\" \"&&\" \"&\"\n  \"<\" \"<=\" \">\" \">=\" \"==\" \"!=\"\n  \"+\" \"-\" \"*\" \"/\" \"::\" \":::\"\n  \"**\" \"^\" \"$\" \"@\" \":\" \"!\"\n  \"special\"\n] @operator\n\n; Punctuation\n\n[\n  \"(\"  \")\"\n  \"{\"  \"}\"\n  \"[\"  \"]\"\n  \"[[\" \"]]\"\n] @punctuation.bracket\n\n(comma) @punctuation.delimiter\n\n; Variables\n\n(identifier) @variable\n\n; Functions\n\n(binary_operator\n    lhs: (identifier) @function\n    operator: \"<-\"\n    rhs: (function_definition)\n)\n\n(binary_operator\n    lhs: (identifier) @function\n    operator: \"=\"\n    rhs: (function_definition)\n)\n\n; Calls\n\n(call function: (identifier) @function)\n\n; - `return` is just a regular identifier in our grammar (#189), but people\n;   expect `return()` to be highlighted\n; - We feel confident that we can use `#eq?` here, as other grammars use\n;   `#eq?` and `#match?` predicates already, even though support for predicates\n;   is dependent on the library that binds to tree-sitter's C library, not the\n;   C library itself.\n;   https://github.com/tree-sitter/tree-sitter-javascript/blob/58404d8cf191d69f2674a8fd507bd5776f46cb11/queries/highlights.scm#L65-L67\n;   https://github.com/tree-sitter/tree-sitter-rust/blob/77a3747266f4d621d0757825e6b11edcbf991ca5/queries/highlights.scm#L9-L11\n; - Placed after `(call function: (identifier) @function)` for correct precedence\n(\n    (call function: (identifier) @keyword)\n    (#eq? @keyword \"return\")\n)\n\n; Parameters\n\n(parameters (parameter name: (identifier) @variable.parameter))\n(arguments (argument name: (identifier) @variable.parameter))\n\n; Namespace\n\n(namespace_operator lhs: (identifier) @namespace)\n\n(call\n    function: (namespace_operator rhs: (identifier) @function)\n)\n\n; Keywords\n\n(function_definition name: \"function\" @keyword.function)\n(function_definition name: \"\\\\\" @operator)\n\n[\n  \"in\"\n  (next)\n  (break)\n] @keyword\n\n[\n  \"if\"\n  \"else\"\n] @conditional\n\n[\n  \"while\"\n  \"repeat\"\n  \"for\"\n] @repeat\n\n[\n  (true)\n  (false)\n] @boolean\n\n[\n  (null)\n  (inf)\n  (nan)\n  (na)\n  (dots)\n  (dot_dot_i)\n] @constant.builtin\n\n; Error\n\n(ERROR) @error\n",
	})
}
