//go:build grammar_subset && grammar_subset_luau

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"

func init() { grammarruntime.RegisterLuauSupport() }
