//go:build !grammar_subset || grammar_subset_starlark

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package starlark provides the standalone starlark grammar.
package starlark

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "354d75997fe72c80d9ba253c8cf21e079ddabb44467cb610e029382bdd687040"

func init() {
	grammarruntime.RegisterStarlarkSupport()
	grammarruntime.RegisterBlob("starlark", grammarblobs.Starlark)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("starlark") }
