//go:build !grammar_subset || grammar_subset_starlark

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package starlark provides the standalone starlark grammar.
package starlark

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "55fc1e6df658db6b92217b89871363db732a9a6f7d7fb01a0781c0b4d91e0dde"

func init() {
	grammarruntime.RegisterStarlarkSupport()
	grammarruntime.RegisterBlob("starlark", grammarblobs.Starlark)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("starlark.bin") }
