//go:build !grammar_subset || grammar_subset_authzed

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package authzed provides the standalone authzed grammar.
package authzed

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7bd8bb78da662120c51792dea5631937b18113cb4876db58dca9bf02190549f7"

func init() { ; grammarruntime.RegisterBlob("authzed", grammarblobs.Authzed) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("authzed.bin") }
