//go:build !grammar_subset || grammar_subset_dockerfile

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package dockerfile provides the standalone dockerfile grammar.
package dockerfile

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "82f01f923b6fdfbdaa50de9a75e4b96633040115c9741e5bccb2fefb98fb39f8"

func init() {
	grammarruntime.RegisterDockerfileSupport()
	grammarruntime.RegisterBlob("dockerfile", grammarblobs.Dockerfile)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("dockerfile.bin") }
