//go:build !grammar_subset || grammar_subset_comment

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package comment provides the standalone comment grammar.
package comment

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "13127a5dbbc3ad2df3b87622670314731540469a236f069bda5d8a61743341e5"

func init() {
	grammarruntime.RegisterCommentSupport()
	grammarruntime.RegisterBlob("comment", grammarblobs.Comment)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("comment") }
