//go:build !grammar_subset || grammar_subset_disassembly

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package disassembly provides the standalone disassembly grammar.
package disassembly

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "4fecdd8a984595d391b005cc17016ad2621d6548c86746c647b41ac6da7312de"

func init() {
	grammarruntime.RegisterDisassemblySupport()
	grammarruntime.RegisterBlob("disassembly", grammarblobs.Disassembly)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("disassembly") }
