//go:build !grammar_subset || grammar_subset_dhall

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package dhall provides the standalone dhall grammar.
package dhall

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "4e3fc819b15ab5c7a147112bdde3e18fba690c51d6175326e5fb9c0bf89e8d0f"

func init() {
	grammarruntime.RegisterDhallSupport()
	grammarruntime.RegisterBlob("dhall", grammarblobs.Dhall)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("dhall.bin") }
