//go:build !grammar_subset || grammar_subset_elm

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package elm provides the standalone elm grammar.
package elm

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d406dcbc0567b678b82e6281b3106d7b81c5a9a45e6156c62e4b1523932ffe93"

func init() {
	grammarruntime.RegisterElmSupport()
	grammarruntime.RegisterBlob("elm", grammarblobs.Elm)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("elm") }
