//go:build !grammar_subset || grammar_subset_elm

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package elm provides the standalone elm grammar.
package elm

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1ddf0c6e758b24b406688ec3798d9d554b6073fe723fc074e3f8da35763cc6b8"

func init() {
	grammarruntime.RegisterElmSupport()
	grammarruntime.RegisterBlob("elm", grammarblobs.Elm)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("elm.bin") }
