//go:build !grammar_subset || grammar_subset_nushell

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package nushell provides the standalone nushell grammar.
package nushell

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7cf2b1a53807841828e55428a9ebe22aa8af018b24afd82456ce921e50c3fb3a"

func init() {
	grammarruntime.RegisterNushellSupport()
	grammarruntime.RegisterBlob("nushell", grammarblobs.Nushell)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("nushell.bin") }
