//go:build !grammar_subset || grammar_subset_nushell

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package nushell provides the standalone nushell grammar.
package nushell

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b1c447d1cef9815c095c60d60a68e788f426e43b3510e6893612fef598dd9f4a"

func init() {
	grammarruntime.RegisterNushellSupport()
	grammarruntime.RegisterBlob("nushell", grammarblobs.Nushell)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("nushell") }
