//go:build !grammar_subset || grammar_subset_asm

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package asm provides the standalone asm grammar.
package asm

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7001e89cc1c597efce3143c011d39a40855067fb06863b738d2c4d7e595fb71d"

func init() { ; grammarruntime.RegisterBlob("asm", grammarblobs.Asm) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("asm") }
