//go:build !grammar_subset || grammar_subset_chatito

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package chatito provides the standalone chatito grammar.
package chatito

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "84646adf323fccb9c812bfcafb9d7a178ab5f835bd7fc0b8bf7173d0811d2afd"

func init() { ; grammarruntime.RegisterBlob("chatito", grammarblobs.Chatito) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("chatito") }
