//go:build !grammar_subset || grammar_subset_glsl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package glsl provides the standalone glsl grammar.
package glsl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "6a1e246dec6015d4b5775e9fb4889b526e403088f59eb03d13a9597e78cc40a7"

func init() { ; grammarruntime.RegisterBlob("glsl", grammarblobs.Glsl) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("glsl.bin") }
