//go:build !grammar_subset || grammar_subset_cylc

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cylc provides the standalone cylc grammar.
package cylc

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "f2b7355774a30d2cac7fb5a3f9fa6753fa968e1b7651f66d69dcff5c35fe6c39"

func init() { ; grammarruntime.RegisterBlob("cylc", grammarblobs.Cylc) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cylc.bin") }
