//go:build !grammar_subset || grammar_subset_cylc

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cylc provides the standalone cylc grammar.
package cylc

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d1d26ff50e01ab890f587ef1bd4110bab247642127838a0fb6447a16c06d2d7b"

func init() { ; grammarruntime.RegisterBlob("cylc", grammarblobs.Cylc) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cylc") }
