//go:build !grammar_subset || grammar_subset_ada

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ada provides the standalone ada grammar.
package ada

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "fbb1e5cf6239a98d57d79ec7dfe59f76df1b6acb6f1a7375364c3b7631268491"

func init() { ; grammarruntime.RegisterBlob("ada", grammarblobs.Ada) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ada.bin") }
