//go:build !grammar_subset || grammar_subset_ada

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ada provides the standalone ada grammar.
package ada

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "32f2dd8f0053ffb7e6b7014f6ff2eb7025287c0d5fcdab6ce1f6a694c2d8899e"

func init() { ; grammarruntime.RegisterBlob("ada", grammarblobs.Ada) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ada.bin") }
