//go:build !grammar_subset || grammar_subset_wgsl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package wgsl provides the standalone wgsl grammar.
package wgsl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "bed4620b51ac8e6dde6ea1ed0d14465f8b17ab11c2487a190650ef15abe392eb"

func init() {
	grammarruntime.RegisterWgslSupport()
	grammarruntime.RegisterBlob("wgsl", grammarblobs.Wgsl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("wgsl") }
