//go:build !grammar_subset || grammar_subset_fennel

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package fennel provides the standalone fennel grammar.
package fennel

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "916598fac89928bfbc26e8c1358d52e81911c612021781f5442eaeb5c86e1f7a"

func init() {
	grammarruntime.RegisterFennelSupport()
	grammarruntime.RegisterBlob("fennel", grammarblobs.Fennel)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("fennel.bin") }
