//go:build !grammar_subset || grammar_subset_fennel

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package fennel provides the standalone fennel grammar.
package fennel

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "63c25f9a4e06a7535506ea5601e946e272da3caab60ee8cf1dee9b55a7d568e7"

func init() {
	grammarruntime.RegisterFennelSupport()
	grammarruntime.RegisterBlob("fennel", grammarblobs.Fennel)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("fennel.bin") }
