//go:build !grammar_subset || grammar_subset_cpp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cpp provides the standalone cpp grammar.
package cpp

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ad09ce8ce8c23e412692eef3b9c50a08a978b13f7c31066aed8b7e01a372b883"

func init() {
	grammarruntime.RegisterCppSupport()
	grammarruntime.RegisterBlob("cpp", grammarblobs.Cpp)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cpp.bin") }
