//go:build !grammar_subset || grammar_subset_css

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package css provides the standalone css grammar.
package css

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "14b75aaaf6c6bc675141fedb1e2e0bea4a6a0ba840ac744d61a29b562c33a679"

func init() {
	grammarruntime.RegisterCssSupport()
	grammarruntime.RegisterBlob("css", grammarblobs.Css)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("css.bin") }
