//go:build !grammar_subset || grammar_subset_css

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package css provides the standalone css grammar.
package css

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ac216cbb231ef051ea76e0e039e779a2a887bd94e4362f9894af901138e09426"

func init() {
	grammarruntime.RegisterCssSupport()
	grammarruntime.RegisterBlob("css", grammarblobs.Css)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("css") }
