//go:build !grammar_subset || grammar_subset_gdscript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package gdscript provides the standalone gdscript grammar.
package gdscript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "18ac7fa325fe86af39abec8bfc5668664ee13877e9b55b0198ea4c01f44c643a"

func init() {
	grammarruntime.RegisterGdscriptSupport()
	grammarruntime.RegisterBlob("gdscript", grammarblobs.Gdscript)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("gdscript") }
