//go:build !grammar_subset || grammar_subset_gdscript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package gdscript provides the standalone gdscript grammar.
package gdscript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d401a0515dcfb78902c4e9bea3f5744f7641407a674477e25e59bc66d1986f09"

func init() {
	grammarruntime.RegisterGdscriptSupport()
	grammarruntime.RegisterBlob("gdscript", grammarblobs.Gdscript)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("gdscript.bin") }
