//go:build !grammar_subset || grammar_subset_c

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package c provides the standalone c grammar.
package c

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9aee42825fd1446ce5b754951db26edadcdba5d2f26b61578a30e87ed2dbbd3c"

func init() { ; grammarruntime.RegisterBlob("c", grammarblobs.C) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("c") }
