//go:build !grammar_subset || grammar_subset_requirements

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package requirements provides the standalone requirements grammar.
package requirements

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b091438f4aef14ea50d2e2cfeb27ac16f3531bed7f8df25d17a94148940577d1"

func init() { ; grammarruntime.RegisterBlob("requirements", grammarblobs.Requirements) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("requirements.bin") }
