//go:build !grammar_subset || grammar_subset_requirements

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package requirements provides the standalone requirements grammar.
package requirements

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9f343375e15e27f5127c2ed4e3271923a4fc844c9fe070210356ef5aa3d93b23"

func init() { ; grammarruntime.RegisterBlob("requirements", grammarblobs.Requirements) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("requirements.bin") }
