//go:build !grammar_subset || grammar_subset_dot

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package dot provides the standalone dot grammar.
package dot

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d98235265313326f5c6f9679f6c88a80a5b288c0a86f2141811ed7b5d95fd3d9"

func init() { ; grammarruntime.RegisterBlob("dot", grammarblobs.Dot) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("dot") }
