//go:build !grammar_subset || grammar_subset_dot

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package dot provides the standalone dot grammar.
package dot

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2ca975f6969700e2d0aa0eb7f9139293cbf342094833f57b10af1fb9c999d1cd"

func init() { ; grammarruntime.RegisterBlob("dot", grammarblobs.Dot) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("dot.bin") }
