//go:build !grammar_subset || grammar_subset_ninja

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ninja provides the standalone ninja grammar.
package ninja

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "f7823c3c0ec7e7959c5ca7a0f58a7db882356db6c1e7773ffe1fb5e952da3969"

func init() { ; grammarruntime.RegisterBlob("ninja", grammarblobs.Ninja) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ninja") }
