//go:build !grammar_subset || grammar_subset_ninja

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ninja provides the standalone ninja grammar.
package ninja

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "4e242d85d3c7cd084063f6607fb84e268a6a9ed16ec7d0b5e005e193819abdcf"

func init() { ; grammarruntime.RegisterBlob("ninja", grammarblobs.Ninja) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ninja.bin") }
