//go:build !grammar_subset || grammar_subset_erlang

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package erlang provides the standalone erlang grammar.
package erlang

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "aa63243bd946d324bfb335d84c162cbaf8cc9922feef71de17296a18186ecedf"

func init() {
	grammarruntime.RegisterErlangSupport()
	grammarruntime.RegisterBlob("erlang", grammarblobs.Erlang)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("erlang.bin") }
