//go:build !grammar_subset || grammar_subset_erlang

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package erlang provides the standalone erlang grammar.
package erlang

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "355deb34ae4b9d8e0bf649c1c36096929d5e403107fa3c8b9c2ee82b138dfdc5"

func init() {
	grammarruntime.RegisterErlangSupport()
	grammarruntime.RegisterBlob("erlang", grammarblobs.Erlang)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("erlang.bin") }
