//go:build !grammar_subset || grammar_subset_apex

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package apex provides the standalone apex grammar.
package apex

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "69fc1b577f1f783a204c98719d55d2f15f329d296b9e227d651056ce878c1bd2"

func init() { ; grammarruntime.RegisterBlob("apex", grammarblobs.Apex) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("apex") }
