//go:build !grammar_subset || grammar_subset_capnp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package capnp provides the standalone capnp grammar.
package capnp

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a0839f7c939baf2b96ce25111bfe68e2eb1dbc18baa874d92b843180e660964b"

func init() { ; grammarruntime.RegisterBlob("capnp", grammarblobs.Capnp) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("capnp.bin") }
