//go:build !grammar_subset || grammar_subset_gitignore

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package gitignore provides the standalone gitignore grammar.
package gitignore

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2c71a50b47cca9250cdea219872599a47f18a258fb53469b4923c31d21a3ef9e"

func init() { ; grammarruntime.RegisterBlob("gitignore", grammarblobs.Gitignore) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("gitignore.bin") }
