//go:build !grammar_subset || grammar_subset_kconfig

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package kconfig provides the standalone kconfig grammar.
package kconfig

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "e88f42452a8016745cf351ebd8972413a61e68f86060831dfa46b6e55248164b"

func init() {
	grammarruntime.RegisterKconfigSupport()
	grammarruntime.RegisterBlob("kconfig", grammarblobs.Kconfig)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("kconfig") }
