//go:build !grammar_subset || grammar_subset_kconfig

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package kconfig provides the standalone kconfig grammar.
package kconfig

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9800f2746f0c16d83e4e634bdc307f4bf41e0067f2c320ade775acdb9cc8c50a"

func init() {
	grammarruntime.RegisterKconfigSupport()
	grammarruntime.RegisterBlob("kconfig", grammarblobs.Kconfig)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("kconfig.bin") }
