//go:build !grammar_subset || grammar_subset_racket

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package racket provides the standalone racket grammar.
package racket

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "eda46ace213c5e9f6bf3fd1606efb5c490f380ad7c14fc323e289ab3d001a1e0"

func init() {
	grammarruntime.RegisterRacketSupport()
	grammarruntime.RegisterBlob("racket", grammarblobs.Racket)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("racket.bin") }
