//go:build !grammar_subset || grammar_subset_faust

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package faust provides the standalone faust grammar.
package faust

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "60d7a47c28dbb04d7eb44d1c67901aa9dfcfa607389a395c94458b692a679909"

func init() { ; grammarruntime.RegisterBlob("faust", grammarblobs.Faust) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("faust.bin") }
