//go:build !grammar_subset || grammar_subset_facility

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package facility provides the standalone facility grammar.
package facility

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "13045c68f10516c73ee8ef5dd81d439d230246dcda17dbd01fba625ce0824b23"

func init() { ; grammarruntime.RegisterBlob("facility", grammarblobs.Facility) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("facility") }
