//go:build !grammar_subset || grammar_subset_markdown

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package markdown provides the standalone markdown grammar.
package markdown

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1833730f8a79a665649d7611387cf73b7852d39ad7f04b7d93f2ea7ef022563e"

func init() {
	grammarruntime.RegisterMarkdownSupport()
	grammarruntime.RegisterBlob("markdown", grammarblobs.Markdown)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("markdown.bin") }
