//go:build !grammar_subset || grammar_subset_nickel

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package nickel provides the standalone nickel grammar.
package nickel

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d3cccb1bf9f353d61fac7df9e5b38a352a02e78b7e27c8044f267fbe17d8519e"

func init() {
	grammarruntime.RegisterNickelSupport()
	grammarruntime.RegisterBlob("nickel", grammarblobs.Nickel)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("nickel") }
