//go:build !grammar_subset || grammar_subset_doxygen

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package doxygen provides the standalone doxygen grammar.
package doxygen

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "f175e5e8a6174370b6f1fb8197d571d91579128bb985c9b8d882e899fd128314"

func init() {
	grammarruntime.RegisterDoxygenSupport()
	grammarruntime.RegisterBlob("doxygen", grammarblobs.Doxygen)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("doxygen.bin") }
