//go:build !grammar_subset || grammar_subset_doxygen

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package doxygen provides the standalone doxygen grammar.
package doxygen

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "84285f8d8a5ddeb9962d399fc5a9b738bf7947582f9a66f1fa9183bb831529cd"

func init() {
	grammarruntime.RegisterDoxygenSupport()
	grammarruntime.RegisterBlob("doxygen", grammarblobs.Doxygen)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("doxygen.bin") }
