//go:build !grammar_subset || grammar_subset_lua

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package lua provides the standalone lua grammar.
package lua

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "97b34a25e0877d92ba7d690c91638b59fe5f397bd8c25f6b9f73f073b6f7fc1e"

func init() {
	grammarruntime.RegisterLuaSupport()
	grammarruntime.RegisterBlob("lua", grammarblobs.Lua)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("lua") }
