//go:build !grammar_subset || grammar_subset_robot

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package robot provides the standalone robot grammar.
package robot

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "25075ecf5323eeb88af4f71b55f51867cef38a277aaa60f01b879ee8abb4c74f"

func init() { ; grammarruntime.RegisterBlob("robot", grammarblobs.Robot) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("robot") }
