//go:build !grammar_subset || grammar_subset_yaml

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package yaml provides the standalone yaml grammar.
package yaml

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9ac37a326be7a4f4297efa6e43ba00317c5959e7b4909c9262043d408f284b30"

func init() {
	grammarruntime.RegisterYamlSupport()
	grammarruntime.RegisterBlob("yaml", grammarblobs.Yaml)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("yaml.bin") }
