//go:build !grammar_subset || grammar_subset_dart

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package dart provides the standalone dart grammar.
package dart

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a58e9eec2f520b8bfde15aec7a7064b25e5c8927fe9edcd87d6ec8562c554ec0"

func init() {
	grammarruntime.RegisterDartSupport()
	grammarruntime.RegisterBlob("dart", grammarblobs.Dart)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("dart.bin") }
