//go:build !grammar_subset || grammar_subset_dart

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package dart provides the standalone dart grammar.
package dart

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "06bac15a9921a2e6af2810fb37ecb29a358b120e137345b9af5fb5f6c6632f59"

func init() {
	grammarruntime.RegisterDartSupport()
	grammarruntime.RegisterBlob("dart", grammarblobs.Dart)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("dart.bin") }
