//go:build !grammar_subset || grammar_subset_sparql

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package sparql provides the standalone sparql grammar.
package sparql

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "84d26d2003614ee278cda3c9d0f133935bd2eb83f9c17b341bb89052e75052b8"

func init() { ; grammarruntime.RegisterBlob("sparql", grammarblobs.Sparql) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("sparql") }
