//go:build !grammar_subset || grammar_subset_scss

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package scss provides the standalone scss grammar.
package scss

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "978678ac7c13f48fb210b0fb59ccc18faa3fa513b3a8ca8e61032af576aadbf2"

func init() {
	grammarruntime.RegisterScssSupport()
	grammarruntime.RegisterBlob("scss", grammarblobs.Scss)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("scss.bin") }
