//go:build !grammar_subset || grammar_subset_scss

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package scss provides the standalone scss grammar.
package scss

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "0646d27248a96d865a717a2a020ede70762b8a0542fac32a316b34248af9a50e"

func init() {
	grammarruntime.RegisterScssSupport()
	grammarruntime.RegisterBlob("scss", grammarblobs.Scss)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("scss.bin") }
