//go:build !grammar_subset || grammar_subset_nginx

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package nginx provides the standalone nginx grammar.
package nginx

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "bf0ef6a27b4d4397a0f0ba5498042b611f97b62c636bf2afe1bbb7fd6489702c"

func init() {
	grammarruntime.RegisterNginxSupport()
	grammarruntime.RegisterBlob("nginx", grammarblobs.Nginx)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("nginx.bin") }
