//go:build !grammar_subset || grammar_subset_nginx

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package nginx provides the standalone nginx grammar.
package nginx

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8c59599851f1c090b80e419843888bb1ebbc89cd7e2dec4451deff75ef446c17"

func init() {
	grammarruntime.RegisterNginxSupport()
	grammarruntime.RegisterBlob("nginx", grammarblobs.Nginx)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("nginx.bin") }
