//go:build !grammar_subset || grammar_subset_rescript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package rescript provides the standalone rescript grammar.
package rescript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3d06d82bc0923ee5616fefd3b379d96a55e2d90384d7db863e0b1b8be24bb99d"

func init() {
	grammarruntime.RegisterRescriptSupport()
	grammarruntime.RegisterBlob("rescript", grammarblobs.Rescript)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("rescript.bin") }
