//go:build !grammar_subset || grammar_subset_cmake

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cmake provides the standalone cmake grammar.
package cmake

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "de536323fb3fa89451fba03cd6accdbd4be42110793a25320987b5a9a50d32e2"

func init() {
	grammarruntime.RegisterCmakeSupport()
	grammarruntime.RegisterBlob("cmake", grammarblobs.Cmake)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cmake") }
