//go:build !grammar_subset || grammar_subset_uxntal

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package uxntal provides the standalone uxntal grammar.
package uxntal

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "cca71a0e6385fd9b2791eb6fefc1fe493f93eb2bf58e903f8989096884c31fe4"

func init() {
	grammarruntime.RegisterUxntalSupport()
	grammarruntime.RegisterBlob("uxntal", grammarblobs.Uxntal)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("uxntal") }
