//go:build !grammar_subset || grammar_subset_desktop

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package desktop provides the standalone desktop grammar.
package desktop

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "5c8a77022a571d6cf00a0ca29d16761c153cbf67a1da1a892609eb56f4d00c11"

func init() { ; grammarruntime.RegisterBlob("desktop", grammarblobs.Desktop) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("desktop") }
