// Command gen_grammar_packages generates standalone grammar packages and compatibility declarations.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const marker = "// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.\n"

func forwarders(fs *token.FileSet, file *ast.File, src []byte) []byte {
	var body strings.Builder
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if ast.IsExported(s.Name.Name) {
						fmt.Fprintf(&body, "type %s = grammarruntime.%s\n", s.Name, s.Name)
					}
				case *ast.ValueSpec:
					for _, name := range s.Names {
						if !ast.IsExported(name.Name) {
							continue
						}
						if d.Tok == token.VAR {
							panic("review exported mutable variable: " + name.Name)
						}
						fmt.Fprintf(&body, "const %s = grammarruntime.%s\n", name, name)
					}
				}
			}
		case *ast.FuncDecl:
			if d.Recv != nil || !ast.IsExported(d.Name.Name) {
				continue
			}
			var args []string
			for i, field := range d.Type.Params.List {
				if len(field.Names) == 0 {
					field.Names = []*ast.Ident{ast.NewIdent(fmt.Sprintf("arg%d", i))}
				}
				for j, name := range field.Names {
					if name.Name == "_" {
						field.Names[j] = ast.NewIdent(fmt.Sprintf("arg%d_%d", i, j))
					}
					arg := field.Names[j].Name
					if _, ok := field.Type.(*ast.Ellipsis); ok {
						arg += "..."
					}
					args = append(args, arg)
				}
			}
			var signature bytes.Buffer
			must(format.Node(&signature, fs, d.Type))
			result := ""
			if d.Type.Results != nil && len(d.Type.Results.List) > 0 {
				result = "return "
			}
			fmt.Fprintf(&body, "func %s%s { %sgrammarruntime.%s(%s) }\n", d.Name, strings.TrimPrefix(signature.String(), "func"), result, d.Name, strings.Join(args, ","))
		}
	}
	if body.Len() == 0 {
		return nil
	}
	var out strings.Builder
	for _, line := range strings.Split(string(src), "\n") {
		if strings.HasPrefix(line, "//go:build ") {
			out.WriteString(line + "\n\n")
			break
		}
	}
	out.WriteString("// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.\n\npackage grammars\n\nimport (\n")
	out.WriteString("grammarruntime \"github.com/odvcencio/gotreesitter/grammars/runtime\"\n")
	for _, imp := range file.Imports {
		path, err := strconv.Unquote(imp.Path.Value)
		must(err)
		name := filepath.Base(path)
		if imp.Name != nil {
			name = imp.Name.Name
		}
		if name == "_" || name == "." || !strings.Contains(body.String(), name+".") {
			continue
		}
		fmt.Fprintf(&out, "%s %q\n", name, path)
	}
	out.WriteString(")\n" + body.String())
	formatted, err := format.Source([]byte(out.String()))
	must(err)
	return formatted
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	check := flag.Bool("check", false, "check generated files without writing changes")
	flag.Parse()
	if err := generate(*check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(check bool) error {
	outputs := map[string][]byte{}
	supports := map[string]string{}
	supportFiles, err := filepath.Glob("grammars/runtime/support_*.go")
	if err != nil {
		return err
	}
	var builtin strings.Builder
	builtin.WriteString("//go:build !grammar_subset\n\n" + marker + "\npackage grammarruntime\n\nfunc RegisterBuiltinScanners() {\n")
	for _, path := range supportFiles {
		name := strings.TrimSuffix(strings.TrimPrefix(filepath.Base(path), "support_"), ".go")
		fn := "Register" + strings.ToUpper(name[:1]) + name[1:] + "Support"
		supports[name] = fn
		fmt.Fprintf(&builtin, "%s()\n", fn)
		subset := fmt.Sprintf("//go:build grammar_subset && grammar_subset_%s\n\n%s\npackage grammars\nimport grammarruntime %q\nfunc init() { grammarruntime.%s() }\n", name, marker, "github.com/odvcencio/gotreesitter/grammars/runtime", fn)
		formatted, err := format.Source([]byte(subset))
		if err != nil {
			return err
		}
		outputs["grammars/z_subset_scanner_register_"+name+".go"] = formatted
	}
	builtin.WriteString("}\n")
	formatted, err := format.Source([]byte(builtin.String()))
	if err != nil {
		return err
	}
	outputs["grammars/runtime/builtin_scanners_gen.go"] = formatted
	blobs, err := filepath.Glob("grammars/grammar_blobs/*.bin")
	if err != nil {
		return err
	}
	if len(blobs) == 0 {
		return fmt.Errorf("no grammar blobs found; run from the repository root")
	}
	for _, path := range blobs {
		name := strings.TrimSuffix(filepath.Base(path), ".bin")
		if !token.IsIdentifier(name) && name != "go" {
			return fmt.Errorf("invalid grammar name %q", name)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		accessor := strings.ToUpper(name[:1]) + name[1:]
		setup := ""
		if fn := supports[name]; fn != "" {
			setup = "grammarruntime." + fn + "()"
		}
		blob := fmt.Sprintf(`%spackage grammarblobs
import _ "embed"
//go:embed %s.bin
var blob%s []byte
// %s returns an independent copy of the %s grammar blob.
func %s() []byte { return append([]byte(nil), blob%s...) }
`, marker, name, accessor, accessor, name, accessor, accessor)
		pkg := name
		if token.Lookup(pkg).IsKeyword() {
			pkg += "lang"
		}
		wrapper := fmt.Sprintf(`//go:build !grammar_subset || grammar_subset_%s

%s// Package %s provides the standalone %s grammar.
package %s
import (
"github.com/odvcencio/gotreesitter"
grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)
// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "%x"
func init() { %s; grammarruntime.RegisterBlob(%q, grammarblobs.%s) }
// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language(%q) }
`, name, marker, pkg, name, pkg, sha256.Sum256(data), setup, name, accessor, name+".bin")
		for path, source := range map[string]string{
			"grammars/grammar_blobs/" + name + ".go": blob,
			"grammars/" + name + "/" + name + ".go":  wrapper,
		} {
			formatted, err := format.Source([]byte(source))
			if err != nil {
				return fmt.Errorf("format %s: %w", path, err)
			}
			outputs[path] = formatted
		}
	}
	runtimeFiles, err := filepath.Glob("grammars/runtime/*.go")
	if err != nil {
		return err
	}
	for _, path := range runtimeFiles {
		if strings.HasPrefix(filepath.Base(path), "support_") || filepath.Base(path) == "builtin_scanners_gen.go" {
			continue
		}
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		// These APIs connect package boundaries. They were not aggregate APIs.
		if filepath.Base(path) == "blob_source.go" || filepath.Base(path) == "token_source_factory_registry.go" {
			continue
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		fs := token.NewFileSet()
		file, err := parser.ParseFile(fs, path, src, parser.ParseComments)
		if err != nil {
			return err
		}
		if wrapper := forwarders(fs, file, src); wrapper != nil {
			outputs["grammars/"+filepath.Base(path)] = wrapper
		}
	}
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		old, err := os.ReadFile(path)
		if err == nil && bytes.Equal(old, outputs[path]) {
			continue
		}
		if check {
			return fmt.Errorf("generated file differs: %s", path)
		}
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(path, outputs[path], 0644); err != nil {
			return err
		}
	}
	// Delete only obsolete files owned by this generator.
	err = filepath.WalkDir("grammars", func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".go") || outputs[path] != nil {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Contains(data, []byte(marker)) {
			return nil
		}
		if check {
			return fmt.Errorf("obsolete generated file: %s", path)
		}
		return os.Remove(path)
	})
	if err != nil {
		return err
	}
	fmt.Printf("checked %d grammar packages and %d generated files\n", len(blobs), len(outputs))
	return nil
}
