//go:build !grammar_subset || grammar_subset_hack

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package hack provides the standalone hack grammar.
package hack

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "f7388868d68644eff2ef6aa3dee5d0da1bc4f926ef4a8b04f98274bd471df3e6"

func init() {
	grammarruntime.RegisterHackSupport()
	grammarruntime.RegisterBlob("hack", grammarblobs.Hack)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("hack") }
