//go:build !grammar_subset || grammar_subset_pem

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package pem provides the standalone pem grammar.
package pem

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b82b79a9e4c4c0854be50f15186b5a6287b718541437a7487c61d89c2895959f"

func init() { ; grammarruntime.RegisterBlob("pem", grammarblobs.Pem) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("pem.bin") }
