//go:build !grammar_subset || grammar_subset_c_sharp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package c_sharp provides the standalone c_sharp grammar.
package c_sharp

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7ad425e89733339dde94e3c03b762ae478fb453b530493f5d62e1ae7537e1784"

func init() {
	grammarruntime.RegisterC_sharpSupport()
	grammarruntime.RegisterBlob("c_sharp", grammarblobs.C_sharp)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("c_sharp") }
