//go:build !grammar_subset || grammar_subset_c_sharp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package c_sharp provides the standalone c_sharp grammar.
package c_sharp

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "198db0d7544ae78c6ba533889e972d4371bdbcaba5d438e6f51e6cb95fff9bcf"

func init() {
	grammarruntime.RegisterC_sharpSupport()
	grammarruntime.RegisterBlob("c_sharp", grammarblobs.C_sharp)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("c_sharp.bin") }
