//go:build !grammar_subset || grammar_subset_html

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package html provides the standalone html grammar.
package html

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "76d3d788ec44b5eaeaa0b3b0069bf52ffc4b125791059ff743301b9938dffd3d"

func init() {
	grammarruntime.RegisterHtmlSupport()
	grammarruntime.RegisterBlob("html", grammarblobs.Html)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("html") }
