//go:build !grammar_subset || grammar_subset_julia

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package julia provides the standalone julia grammar.
package julia

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "523f468e74a975803e6afd08eb0f8d59de2e807ebe4b3f38633cb2d6bf35198d"

func init() {
	grammarruntime.RegisterJuliaSupport()
	grammarruntime.RegisterBlob("julia", grammarblobs.Julia)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("julia.bin") }
