//go:build !grammar_subset || grammar_subset_julia

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package julia provides the standalone julia grammar.
package julia

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "c716f2b9ee3852cc25a26107b7a1c78b9f76585fa77774d8f8a1b47ad590134f"

func init() {
	grammarruntime.RegisterJuliaSupport()
	grammarruntime.RegisterBlob("julia", grammarblobs.Julia)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("julia") }
