//go:build !grammar_subset || grammar_subset_rst

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package rst provides the standalone rst grammar.
package rst

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "73d1733b72e69213c64152ad98061d1910b75081220f4e7093e8feb860854b31"

func init() {
	grammarruntime.RegisterRstSupport()
	grammarruntime.RegisterBlob("rst", grammarblobs.Rst)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("rst") }
