//go:build !grammar_subset || grammar_subset_rst

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package rst provides the standalone rst grammar.
package rst

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "5ff932e4e0a59bbdf985ac0d970fd8af628ea1d3c996fc45deaf8a2665f5ffb7"

func init() {
	grammarruntime.RegisterRstSupport()
	grammarruntime.RegisterBlob("rst", grammarblobs.Rst)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("rst.bin") }
