//go:build !grammar_subset || grammar_subset_angular

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package angular provides the standalone angular grammar.
package angular

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "511f88a60df94ee8fbc6ae1822e0b58b74a90885d0d7b11e0fdc43e7d26292a9"

func init() {
	grammarruntime.RegisterAngularSupport()
	grammarruntime.RegisterBlob("angular", grammarblobs.Angular)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("angular.bin") }
