//go:build !grammar_subset || grammar_subset_angular

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package angular provides the standalone angular grammar.
package angular

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a298b788ab953e5bade3f20496a94f8e3284157f34710264cf72b58bd893d049"

func init() {
	grammarruntime.RegisterAngularSupport()
	grammarruntime.RegisterBlob("angular", grammarblobs.Angular)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("angular") }
