//go:build !grammar_subset || grammar_subset_matlab

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package matlab provides the standalone matlab grammar.
package matlab

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "c24998057aece56828f0fa36806b95ca90f4aec0c782095f1d6003c3bb40b611"

func init() {
	grammarruntime.RegisterMatlabSupport()
	grammarruntime.RegisterBlob("matlab", grammarblobs.Matlab)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("matlab.bin") }
