//go:build !grammar_subset || grammar_subset_pascal

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package pascal provides the standalone pascal grammar.
package pascal

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "74edaca0760bff18fc95a9bdf32c8ea7eee8bc8126f76089b790a792c70b61ac"

func init() { ; grammarruntime.RegisterBlob("pascal", grammarblobs.Pascal) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("pascal.bin") }
