//go:build !grammar_subset || grammar_subset_pascal

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package pascal provides the standalone pascal grammar.
package pascal

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8003a718f6750b321ad1e3d71f189c360284a46d756d3515236c15b4275141f1"

func init() { ; grammarruntime.RegisterBlob("pascal", grammarblobs.Pascal) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("pascal.bin") }
