//go:build !grammar_subset || grammar_subset_ledger

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ledger provides the standalone ledger grammar.
package ledger

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "f525c8446824ce33da625a924f966041cd0d02f8f3ee29f90fce8bf1f53d69c2"

func init() { ; grammarruntime.RegisterBlob("ledger", grammarblobs.Ledger) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ledger.bin") }
