//go:build !grammar_subset || grammar_subset_ledger

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ledger provides the standalone ledger grammar.
package ledger

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7239a4ece2871120ec7f7b8049f610e01736fc0c14a9f55d2a7e9d75d650a098"

func init() { ; grammarruntime.RegisterBlob("ledger", grammarblobs.Ledger) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ledger") }
