//go:build !grammar_subset || grammar_subset_cpon

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cpon provides the standalone cpon grammar.
package cpon

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b7ab1b403a1b0773ad73d760db54c3691e83cd1b507588642a272f0d3005c5cd"

func init() { ; grammarruntime.RegisterBlob("cpon", grammarblobs.Cpon) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cpon") }
