//go:build !grammar_subset || grammar_subset_hurl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package hurl provides the standalone hurl grammar.
package hurl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "50d9954a4fc46aa32745cfe4b96fb99918a1668b5f554a395d9d4d70ae3a938b"

func init() { ; grammarruntime.RegisterBlob("hurl", grammarblobs.Hurl) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("hurl.bin") }
