//go:build !grammar_subset || grammar_subset_hurl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package hurl provides the standalone hurl grammar.
package hurl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8de06e2e5cbb1f5c3274e23314ee8606ca284e5c990fdcce1acd1f42f45f6a6b"

func init() { ; grammarruntime.RegisterBlob("hurl", grammarblobs.Hurl) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("hurl.bin") }
