//go:build !grammar_subset || grammar_subset_agda

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package agda provides the standalone agda grammar.
package agda

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "dfa9e4bbccc88516d47bde22fcf5cc2d8822d84b80d3d4cb0ea76079e1cc0377"

func init() {
	grammarruntime.RegisterAgdaSupport()
	grammarruntime.RegisterBlob("agda", grammarblobs.Agda)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("agda.bin") }
