//go:build !grammar_subset || grammar_subset_embedded_template

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package embedded_template provides the standalone embedded_template grammar.
package embedded_template

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "afc2aea83a5609302c604c6fdf949ef6f3663564ed8f9df16f900fd8b30da955"

func init() { ; grammarruntime.RegisterBlob("embedded_template", grammarblobs.Embedded_template) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("embedded_template.bin") }
