//go:build !grammar_subset || grammar_subset_tmux

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package tmux provides the standalone tmux grammar.
package tmux

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3b8ac4ea321cc9af826950605b786f79681a4dc2e1c941c9add9ccf4cec7540a"

func init() { ; grammarruntime.RegisterBlob("tmux", grammarblobs.Tmux) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("tmux") }
