//go:build !grammar_subset || grammar_subset_tmux

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package tmux provides the standalone tmux grammar.
package tmux

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "c96857c53b1c8421068ede1aa82f3d1368e967bc5ae41baf1feff67a165cf1d1"

func init() { ; grammarruntime.RegisterBlob("tmux", grammarblobs.Tmux) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("tmux.bin") }
