//go:build !grammar_subset || grammar_subset_ql

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ql provides the standalone ql grammar.
package ql

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "f9e092262139d482fef46ef6274a2ac90f9344ea13766d6528819a4e21e7cc84"

func init() { ; grammarruntime.RegisterBlob("ql", grammarblobs.Ql) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ql") }
