//go:build !grammar_subset || grammar_subset_sql

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package sql provides the standalone sql grammar.
package sql

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "98e31a623b335e58132cf273eb87c400cf5f0a1f2e5b67c8df69b04b58df02f1"

func init() {
	grammarruntime.RegisterSqlSupport()
	grammarruntime.RegisterBlob("sql", grammarblobs.Sql)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("sql.bin") }
