//go:build !grammar_subset || grammar_subset_sql

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package sql provides the standalone sql grammar.
package sql

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "e21421cbab52b54cf5ba15c8f78a2bb4729bf4e8c0da14368069e897de451268"

func init() {
	grammarruntime.RegisterSqlSupport()
	grammarruntime.RegisterBlob("sql", grammarblobs.Sql)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("sql") }
