//go:build !grammar_subset || grammar_subset_pkl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package pkl provides the standalone pkl grammar.
package pkl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "6df6a678a21c14a87966622e00a066c0446d71cb3ccfb152d556f584a2f0f477"

func init() {
	grammarruntime.RegisterPklSupport()
	grammarruntime.RegisterBlob("pkl", grammarblobs.Pkl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("pkl") }
