//go:build !grammar_subset || grammar_subset_heex

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package heex provides the standalone heex grammar.
package heex

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a545e5a75a2fd8e7b7e36a3c75ebf037e06f2b8414d3550ae49a80a096845b9d"

func init() { ; grammarruntime.RegisterBlob("heex", grammarblobs.Heex) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("heex.bin") }
