//go:build !grammar_subset || grammar_subset_heex

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package heex provides the standalone heex grammar.
package heex

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2d47af7b1409c24e7ffbb4523896b88acf5b067671123ff69439977e1d5d352d"

func init() { ; grammarruntime.RegisterBlob("heex", grammarblobs.Heex) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("heex") }
