//go:build !grammar_subset || grammar_subset_scala

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package scala provides the standalone scala grammar.
package scala

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8bc4a20f983ea8c8873c28430f089ba2bbbf00a995dd29f575bf2bc598d29dfa"

func init() {
	grammarruntime.RegisterScalaSupport()
	grammarruntime.RegisterBlob("scala", grammarblobs.Scala)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("scala") }
