//go:build !grammar_subset || grammar_subset_typescript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package typescript provides the standalone typescript grammar.
package typescript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "24cd3db3cc41a451b2733fbd7b210e8c889df04a7e68204c7a93e90364cf6de7"

func init() {
	grammarruntime.RegisterTypescriptSupport()
	grammarruntime.RegisterBlob("typescript", grammarblobs.Typescript)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("typescript.bin") }
