//go:build !grammar_subset || grammar_subset_typescript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package typescript provides the standalone typescript grammar.
package typescript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "266858bd541845ef50549e5a6ed218ae977c44ec02e7007c7ea430fb4ba73c3f"

func init() {
	grammarruntime.RegisterTypescriptSupport()
	grammarruntime.RegisterBlob("typescript", grammarblobs.Typescript)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("typescript.bin") }
