//go:build !grammar_subset || grammar_subset_typescript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package typescript provides the standalone typescript grammar.
package typescript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1b6ace3de973196290411c0347013b9f2cc2385171c77dcf375e355f3c2cc90c"

func init() {
	grammarruntime.RegisterTypescriptSupport()
	grammarruntime.RegisterBlob("typescript", grammarblobs.Typescript)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("typescript.bin") }
