//go:build !grammar_subset || grammar_subset_svelte

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package svelte provides the standalone svelte grammar.
package svelte

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "f0b065092fb9884381cb1e04dcb3bca9fc3b04f1df1dc92addb7afabcf1b2f59"

func init() {
	grammarruntime.RegisterSvelteSupport()
	grammarruntime.RegisterBlob("svelte", grammarblobs.Svelte)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("svelte") }
