//go:build !grammar_subset || grammar_subset_swift

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package swift provides the standalone swift grammar.
package swift

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "be4575bc0acc3c60324aab635d067f940ac5f0557b80a8e3565d1e7d02d53582"

func init() {
	grammarruntime.RegisterSwiftSupport()
	grammarruntime.RegisterBlob("swift", grammarblobs.Swift)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("swift.bin") }
