//go:build !grammar_subset || grammar_subset_swift

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package swift provides the standalone swift grammar.
package swift

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d478cfae88bb00ea664789b3b0c89b99c108f91487e693fd873905d0b9a3c747"

func init() {
	grammarruntime.RegisterSwiftSupport()
	grammarruntime.RegisterBlob("swift", grammarblobs.Swift)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("swift.bin") }
