//go:build !grammar_subset || grammar_subset_puppet

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package puppet provides the standalone puppet grammar.
package puppet

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d6da4f24af1b087906a61b3caa3ed7c62a2b8256b20628c8c465dd082b7ce79a"

func init() { ; grammarruntime.RegisterBlob("puppet", grammarblobs.Puppet) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("puppet.bin") }
