//go:build !grammar_subset || grammar_subset_squirrel

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package squirrel provides the standalone squirrel grammar.
package squirrel

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2c33de9d3e7ed39082456a9e2657c7e053fbcbd2f4071cc2e22d2bb405e6d4d4"

func init() {
	grammarruntime.RegisterSquirrelSupport()
	grammarruntime.RegisterBlob("squirrel", grammarblobs.Squirrel)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("squirrel") }
