//go:build !grammar_subset || grammar_subset_blade

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package blade provides the standalone blade grammar.
package blade

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a89a0cb02098008d5724b72e117ee7eec7232b60699942ee5810bca17f4aa434"

func init() {
	grammarruntime.RegisterBladeSupport()
	grammarruntime.RegisterBlob("blade", grammarblobs.Blade)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("blade.bin") }
