//go:build !grammar_subset || grammar_subset_perl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package perl provides the standalone perl grammar.
package perl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "22388f06c2c54bb4748fd5f5f682ed25eecff8115a7e8e6a98f94f9c94bb9820"

func init() {
	grammarruntime.RegisterPerlSupport()
	grammarruntime.RegisterBlob("perl", grammarblobs.Perl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("perl.bin") }
