//go:build !grammar_subset || grammar_subset_perl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package perl provides the standalone perl grammar.
package perl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "86d67a0890101c16ea75282116915d7fa983272d4c872f404d9fc87ecd3fdea2"

func init() {
	grammarruntime.RegisterPerlSupport()
	grammarruntime.RegisterBlob("perl", grammarblobs.Perl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("perl.bin") }
