//go:build !grammar_subset || grammar_subset_gitcommit

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package gitcommit provides the standalone gitcommit grammar.
package gitcommit

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "739548172c738dfa86c6f4c3177009ba20e5d3c48f5669d5fab478de1db5cca4"

func init() {
	grammarruntime.RegisterGitcommitSupport()
	grammarruntime.RegisterBlob("gitcommit", grammarblobs.Gitcommit)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("gitcommit.bin") }
