//go:build !grammar_subset || grammar_subset_fortran

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package fortran provides the standalone fortran grammar.
package fortran

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "47b5e137e1812731d3760444cb57a7e5c49e0757929b1c8f37e4c16752e5d6c2"

func init() {
	grammarruntime.RegisterFortranSupport()
	grammarruntime.RegisterBlob("fortran", grammarblobs.Fortran)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("fortran.bin") }
