//go:build !grammar_subset || grammar_subset_fortran

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package fortran provides the standalone fortran grammar.
package fortran

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "74374b3b19163e8fc27181fa8b3b848a608a892aaca9d5b9cdf3bf89e9a3e3fc"

func init() {
	grammarruntime.RegisterFortranSupport()
	grammarruntime.RegisterBlob("fortran", grammarblobs.Fortran)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("fortran.bin") }
