//go:build !grammar_subset || grammar_subset_godot_resource

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package godot_resource provides the standalone godot_resource grammar.
package godot_resource

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "cb71e2c9ae95d9dc9b35f0b64013a5a379ed9cdfbf4a374c862c022b4e1949d3"

func init() {
	grammarruntime.RegisterGodot_resourceSupport()
	grammarruntime.RegisterBlob("godot_resource", grammarblobs.Godot_resource)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("godot_resource") }
