//go:build !grammar_subset || grammar_subset_awk

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package awk provides the standalone awk grammar.
package awk

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "925312ca0bc6e279602402c64700b8198c55ed949ac967ce92bae40f7f21cedf"

func init() {
	grammarruntime.RegisterAwkSupport()
	grammarruntime.RegisterBlob("awk", grammarblobs.Awk)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("awk") }
