//go:build !grammar_subset || grammar_subset_tablegen

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package tablegen provides the standalone tablegen grammar.
package tablegen

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "67444eaee648a379d9f40cc3caf69bef392ecbc215e8e8a5610a2ced1080dc67"

func init() {
	grammarruntime.RegisterTablegenSupport()
	grammarruntime.RegisterBlob("tablegen", grammarblobs.Tablegen)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("tablegen") }
