//go:build !grammar_subset || grammar_subset_arduino

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package arduino provides the standalone arduino grammar.
package arduino

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "016d376d3ff424acb48686e4784f72fc6816a9574ca6d51f2787d803cd064f7f"

func init() {
	grammarruntime.RegisterArduinoSupport()
	grammarruntime.RegisterBlob("arduino", grammarblobs.Arduino)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("arduino.bin") }
