//go:build !grammar_subset || grammar_subset_arduino

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package arduino provides the standalone arduino grammar.
package arduino

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8cfea7d98636a7c1916dd9a6b21527f1a59787f730def32feb9a782f2770c102"

func init() {
	grammarruntime.RegisterArduinoSupport()
	grammarruntime.RegisterBlob("arduino", grammarblobs.Arduino)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("arduino.bin") }
