//go:build !grammar_subset || grammar_subset_astro

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package astro provides the standalone astro grammar.
package astro

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "d78bb1428a69bf2986bfe00495b98c399f068e9388b58b2269e9ef067233af42"

func init() {
	grammarruntime.RegisterAstroSupport()
	grammarruntime.RegisterBlob("astro", grammarblobs.Astro)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("astro") }
