//go:build !grammar_subset || grammar_subset_jq

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package jq provides the standalone jq grammar.
package jq

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "da99dda1ffe813f439168944c6b8eae3658a06533b8e10e36115131313a755c3"

func init() { ; grammarruntime.RegisterBlob("jq", grammarblobs.Jq) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("jq") }
