//go:build !grammar_subset || grammar_subset_teal

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package teal provides the standalone teal grammar.
package teal

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b65de455d8a177042af1ad47c2fbfcb8b85e8027ff4b62c8d2397d6c0c5052bb"

func init() {
	grammarruntime.RegisterTealSupport()
	grammarruntime.RegisterBlob("teal", grammarblobs.Teal)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("teal.bin") }
