//go:build !grammar_subset || grammar_subset_teal

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package teal provides the standalone teal grammar.
package teal

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "15ea5eb01e521bf93cb34fe18ca7d6ba9e23a13dc7d244fbed0cbb514c64dc17"

func init() {
	grammarruntime.RegisterTealSupport()
	grammarruntime.RegisterBlob("teal", grammarblobs.Teal)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("teal.bin") }
