//go:build !grammar_subset || grammar_subset_nix

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package nix provides the standalone nix grammar.
package nix

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "4be43cf93ac69d67c35156a335592fe637ef537a90d2e1b6d1ed8beca9387fd2"

func init() {
	grammarruntime.RegisterNixSupport()
	grammarruntime.RegisterBlob("nix", grammarblobs.Nix)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("nix.bin") }
