//go:build !grammar_subset || grammar_subset_bibtex

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package bibtex provides the standalone bibtex grammar.
package bibtex

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8a663bef74f5fc113d6fc278c056c4a4ba064e5690f50b7819c18a59f70393f6"

func init() { ; grammarruntime.RegisterBlob("bibtex", grammarblobs.Bibtex) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("bibtex.bin") }
