//go:build !grammar_subset || grammar_subset_markdown_inline

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package markdown_inline provides the standalone markdown_inline grammar.
package markdown_inline

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "33bed84a809d7bd8a321b59b811303de9f494a85f7201e44dad8debf42f3a664"

func init() {
	grammarruntime.RegisterMarkdown_inlineSupport()
	grammarruntime.RegisterBlob("markdown_inline", grammarblobs.Markdown_inline)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("markdown_inline.bin") }
