//go:build !grammar_subset || grammar_subset_zig

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package zig provides the standalone zig grammar.
package zig

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "90233f784fb813287e625e09219ddcc08bec5d3f526094330222b7c894d90f48"

func init() { ; grammarruntime.RegisterBlob("zig", grammarblobs.Zig) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("zig.bin") }
