//go:build !grammar_subset || grammar_subset_zig

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package zig provides the standalone zig grammar.
package zig

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "11e45b784b2056d8a3d60e4f184b1f519146f6a97fd4909cf024f702c38fa21a"

func init() { ; grammarruntime.RegisterBlob("zig", grammarblobs.Zig) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("zig.bin") }
