//go:build !grammar_subset || grammar_subset_purescript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package purescript provides the standalone purescript grammar.
package purescript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "001b2d0e638c1cafcc09b871c74891290d037f3638670e0562e3f1da0f7918a4"

func init() {
	grammarruntime.RegisterPurescriptSupport()
	grammarruntime.RegisterBlob("purescript", grammarblobs.Purescript)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("purescript.bin") }
