//go:build !grammar_subset || grammar_subset_purescript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package purescript provides the standalone purescript grammar.
package purescript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b1e682a3f80fcbe7f9c58e034551f2d2cabc0c8cea379a3a910e0df07ac898af"

func init() {
	grammarruntime.RegisterPurescriptSupport()
	grammarruntime.RegisterBlob("purescript", grammarblobs.Purescript)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("purescript") }
