//go:build !grammar_subset || grammar_subset_prisma

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package prisma provides the standalone prisma grammar.
package prisma

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b42dbaed4782ba5ea8f2fd7715062f89f33738faaafebb3cebf003a0f0396ad6"

func init() { ; grammarruntime.RegisterBlob("prisma", grammarblobs.Prisma) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("prisma.bin") }
