//go:build !grammar_subset || grammar_subset_python

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package python provides the standalone python grammar.
package python

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a74155ab219de90df1fcd1320397bb466949fed5cfa177823ac41ba1b75ff60b"

func init() {
	grammarruntime.RegisterPythonSupport()
	grammarruntime.RegisterBlob("python", grammarblobs.Python)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("python.bin") }
