//go:build !grammar_subset || grammar_subset_rego

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package rego provides the standalone rego grammar.
package rego

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "b10816c87dc847492fbbc1fd97c5096ed35d7abe69d0cd2ef5dd7e02aabac25c"

func init() { ; grammarruntime.RegisterBlob("rego", grammarblobs.Rego) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("rego.bin") }
