//go:build !grammar_subset || grammar_subset_textproto

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package textproto provides the standalone textproto grammar.
package textproto

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "38b3e0f80abf77c94685f4de615c732a56dde0809d79f68aa9dce705df622dde"

func init() { ; grammarruntime.RegisterBlob("textproto", grammarblobs.Textproto) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("textproto.bin") }
