//go:build !grammar_subset || grammar_subset_powershell

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package powershell provides the standalone powershell grammar.
package powershell

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8c7a2b47a39efb590cde7f75c9a1135c6423bc07b13b9604f1fa9f0061231687"

func init() {
	grammarruntime.RegisterPowershellSupport()
	grammarruntime.RegisterBlob("powershell", grammarblobs.Powershell)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("powershell.bin") }
