//go:build !grammar_subset || grammar_subset_powershell

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package powershell provides the standalone powershell grammar.
package powershell

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "bb15be2e939a75bc80ea56d6606f43dea101bf7437ac82073f61985c4dee2492"

func init() {
	grammarruntime.RegisterPowershellSupport()
	grammarruntime.RegisterBlob("powershell", grammarblobs.Powershell)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("powershell.bin") }
