//go:build !grammar_subset || grammar_subset_foam

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package foam provides the standalone foam grammar.
package foam

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "eb82be44345c6d4e8c242e95cb37814b1d4acb77182e5add91904509c7e325d8"

func init() {
	grammarruntime.RegisterFoamSupport()
	grammarruntime.RegisterBlob("foam", grammarblobs.Foam)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("foam") }
