//go:build !grammar_subset || grammar_subset_scheme

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package scheme provides the standalone scheme grammar.
package scheme

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "79802f112fbdd405a0237eb7e484a95ae4f8fd608b17859c968b2aba38db4b23"

func init() { ; grammarruntime.RegisterBlob("scheme", grammarblobs.Scheme) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("scheme.bin") }
