//go:build !grammar_subset || grammar_subset_norg

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package norg provides the standalone norg grammar.
package norg

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7e1d885c9b09a50525df5ac246696d4f969418f79799497a391ade9caa8f1915"

func init() {
	grammarruntime.RegisterNorgSupport()
	grammarruntime.RegisterBlob("norg", grammarblobs.Norg)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("norg.bin") }
