//go:build !grammar_subset || grammar_subset_norg

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package norg provides the standalone norg grammar.
package norg

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "0a226ea2ffe779d8844894a1df9fc9814441bdcb7060f1820a25375c16867fb9"

func init() {
	grammarruntime.RegisterNorgSupport()
	grammarruntime.RegisterBlob("norg", grammarblobs.Norg)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("norg.bin") }
