//go:build !grammar_subset || grammar_subset_just

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package just provides the standalone just grammar.
package just

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "565a91fc1ba228084d0fd192071e5de401ed69477bcf313c1460aa119e3e6005"

func init() {
	grammarruntime.RegisterJustSupport()
	grammarruntime.RegisterBlob("just", grammarblobs.Just)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("just.bin") }
