//go:build !grammar_subset || grammar_subset_cobol

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cobol provides the standalone cobol grammar.
package cobol

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9d5a743e119dda948c2c63e0a1fba8f0f55cbc67c262d658cb96539d07aa9398"

func init() {
	grammarruntime.RegisterCobolSupport()
	grammarruntime.RegisterBlob("cobol", grammarblobs.Cobol)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cobol") }
