//go:build !grammar_subset || grammar_subset_ini

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ini provides the standalone ini grammar.
package ini

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "889b7add01c97922db1579ca2328290400b2636856b4650cffb1756fb12d759b"

func init() { ; grammarruntime.RegisterBlob("ini", grammarblobs.Ini) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ini.bin") }
