//go:build !grammar_subset || grammar_subset_cairo

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cairo provides the standalone cairo grammar.
package cairo

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ee894609099ca1afcd93337a4faeb9b351dab44a7b19c07d1961a88bf2df9378"

func init() {
	grammarruntime.RegisterCairoSupport()
	grammarruntime.RegisterBlob("cairo", grammarblobs.Cairo)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cairo.bin") }
