//go:build !grammar_subset || grammar_subset_cairo

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package cairo provides the standalone cairo grammar.
package cairo

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "1a5a4cce20bd003fb0d043e75a24540005b0172bbda618df1586f27d73c97baf"

func init() {
	grammarruntime.RegisterCairoSupport()
	grammarruntime.RegisterBlob("cairo", grammarblobs.Cairo)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("cairo.bin") }
