//go:build !grammar_subset || grammar_subset_kdl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package kdl provides the standalone kdl grammar.
package kdl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "ef6d000123c053eddebd200a1cbd44d6df5dcab7c4b3d34ae18acdf2f14989f5"

func init() {
	grammarruntime.RegisterKdlSupport()
	grammarruntime.RegisterBlob("kdl", grammarblobs.Kdl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("kdl.bin") }
