//go:build !grammar_subset || grammar_subset_kdl

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package kdl provides the standalone kdl grammar.
package kdl

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7e993a017c7e5e7cf192833fc57614731558662cea07bf419d5c663258bf15ee"

func init() {
	grammarruntime.RegisterKdlSupport()
	grammarruntime.RegisterBlob("kdl", grammarblobs.Kdl)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("kdl.bin") }
