//go:build !grammar_subset || grammar_subset_objc

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package objc provides the standalone objc grammar.
package objc

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "c04e841cf500f2b213d699681930a16f3c5f0e74e60f8a4488c36c38015bc09f"

func init() { ; grammarruntime.RegisterBlob("objc", grammarblobs.Objc) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("objc") }
