//go:build !grammar_subset || grammar_subset_ron

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package ron provides the standalone ron grammar.
package ron

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "f9b7f0a66f46eac09389e915597201883439a8bac428c6e4ac184bbd0113e81b"

func init() {
	grammarruntime.RegisterRonSupport()
	grammarruntime.RegisterBlob("ron", grammarblobs.Ron)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("ron.bin") }
