//go:build !grammar_subset || grammar_subset_wolfram

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package wolfram provides the standalone wolfram grammar.
package wolfram

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "049223fe9382f88405b2758c21811af85cb0a7d771de71970817198ff703c169"

func init() {
	grammarruntime.RegisterWolframSupport()
	grammarruntime.RegisterBlob("wolfram", grammarblobs.Wolfram)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("wolfram") }
