//go:build !grammar_subset || grammar_subset_typst

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package typst provides the standalone typst grammar.
package typst

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "72085d9ceed0ad9fad3ee46107833c18a0f085107f27b9e1eda6775c0fc14c59"

func init() {
	grammarruntime.RegisterTypstSupport()
	grammarruntime.RegisterBlob("typst", grammarblobs.Typst)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("typst.bin") }
