//go:build !grammar_subset || grammar_subset_groovy

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package groovy provides the standalone groovy grammar.
package groovy

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a1d1bb30d9971f1c3d645aab456521943a5f0da419b57a0986fc9b2a502a90d9"

func init() { ; grammarruntime.RegisterBlob("groovy", grammarblobs.Groovy) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("groovy.bin") }
