//go:build !grammar_subset || grammar_subset_groovy

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package groovy provides the standalone groovy grammar.
package groovy

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3f8abf005a63ea535e2966440dfebb495d21a8d78822dab78b14c1b321946957"

func init() { ; grammarruntime.RegisterBlob("groovy", grammarblobs.Groovy) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("groovy.bin") }
