//go:build !grammar_subset || grammar_subset_verilog

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package verilog provides the standalone verilog grammar.
package verilog

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2caa0d9224954120538bf59b6a146f0e25292b16209772b3ba93632e9bf90799"

func init() { ; grammarruntime.RegisterBlob("verilog", grammarblobs.Verilog) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("verilog.bin") }
