//go:build !grammar_subset || grammar_subset_commonlisp

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package commonlisp provides the standalone commonlisp grammar.
package commonlisp

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "df18706a7e77e1927d285a629c7b5809c09139dff169dc5995f780e5a4d0fa0d"

func init() { ; grammarruntime.RegisterBlob("commonlisp", grammarblobs.Commonlisp) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("commonlisp.bin") }
