//go:build !grammar_subset || grammar_subset_bitbake

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package bitbake provides the standalone bitbake grammar.
package bitbake

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7f9f14b2a4d61d5d0572aeec8e2cf06dae7f38939a86a483eaeb79d4ae4e9e32"

func init() {
	grammarruntime.RegisterBitbakeSupport()
	grammarruntime.RegisterBlob("bitbake", grammarblobs.Bitbake)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("bitbake.bin") }
