//go:build !grammar_subset || grammar_subset_bitbake

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package bitbake provides the standalone bitbake grammar.
package bitbake

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "318113b1f31b1cf341701b324c0bb6a975007e5f067d8072faf595ccb42de1c3"

func init() {
	grammarruntime.RegisterBitbakeSupport()
	grammarruntime.RegisterBlob("bitbake", grammarblobs.Bitbake)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("bitbake.bin") }
