//go:build !grammar_subset || grammar_subset_tlaplus

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package tlaplus provides the standalone tlaplus grammar.
package tlaplus

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "32102c6cdebad5e64540882e9d08b769ab093c2cf5a5045070b4e0f4044b3811"

func init() {
	grammarruntime.RegisterTlaplusSupport()
	grammarruntime.RegisterBlob("tlaplus", grammarblobs.Tlaplus)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("tlaplus.bin") }
