//go:build !grammar_subset || grammar_subset_tlaplus

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package tlaplus provides the standalone tlaplus grammar.
package tlaplus

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "423a227c02b0423030a9ed8426c980e11d486d61d869cc4a53abbcb42bf8c378"

func init() {
	grammarruntime.RegisterTlaplusSupport()
	grammarruntime.RegisterBlob("tlaplus", grammarblobs.Tlaplus)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("tlaplus") }
