//go:build !grammar_subset || grammar_subset_forth

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package forth provides the standalone forth grammar.
package forth

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "6795b82a36b4f2ddbe6e45363855a557884282d001a471f9bafe449c9f5b21f2"

func init() { ; grammarruntime.RegisterBlob("forth", grammarblobs.Forth) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("forth") }
