//go:build !grammar_subset || grammar_subset_git_rebase

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package git_rebase provides the standalone git_rebase grammar.
package git_rebase

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2035c9d0444b230cb6c5848f5a18de855feac7394302a7f1d94681ed468d2acb"

func init() { ; grammarruntime.RegisterBlob("git_rebase", grammarblobs.Git_rebase) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("git_rebase.bin") }
