//go:build !grammar_subset || grammar_subset_haskell

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package haskell provides the standalone haskell grammar.
package haskell

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "fcfc8794bca4442ebf5688d88e2397c78a22c8f0b585c4e1b868986cfa52dd09"

func init() {
	grammarruntime.RegisterHaskellSupport()
	grammarruntime.RegisterBlob("haskell", grammarblobs.Haskell)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("haskell") }
