//go:build !grammar_subset || grammar_subset_haskell

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package haskell provides the standalone haskell grammar.
package haskell

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "5e8ac7ac21ebd2e299fa471805498176fecc02c6ccc9eb3422609f0a075c0441"

func init() {
	grammarruntime.RegisterHaskellSupport()
	grammarruntime.RegisterBlob("haskell", grammarblobs.Haskell)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("haskell.bin") }
