//go:build !grammar_subset || grammar_subset_devicetree

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package devicetree provides the standalone devicetree grammar.
package devicetree

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "e473840a6daeb76fcf85e02cbf4e199b28336d1087aa455f10d5fafa7000236c"

func init() { ; grammarruntime.RegisterBlob("devicetree", grammarblobs.Devicetree) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("devicetree.bin") }
