//go:build !grammar_subset || grammar_subset_jsdoc

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package jsdoc provides the standalone jsdoc grammar.
package jsdoc

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "e5688e60d41d6ef2d0922de7687b597de0c880761064e9e7b994d401c5508312"

func init() {
	grammarruntime.RegisterJsdocSupport()
	grammarruntime.RegisterBlob("jsdoc", grammarblobs.Jsdoc)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("jsdoc") }
