//go:build !grammar_subset || grammar_subset_enforce

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package enforce provides the standalone enforce grammar.
package enforce

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9ddb5d9b74c06eb3f3f9eba98be968719eff298d86ee9aa046009ed0a868b676"

func init() { ; grammarruntime.RegisterBlob("enforce", grammarblobs.Enforce) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("enforce.bin") }
