//go:build !grammar_subset || grammar_subset_wat

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package wat provides the standalone wat grammar.
package wat

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "abb45d60f9ee68d3b249c79eedb0ac022f7e02eeaa9a74c37c3db2ec1aa5f5be"

func init() { ; grammarruntime.RegisterBlob("wat", grammarblobs.Wat) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("wat") }
