//go:build !grammar_subset || grammar_subset_php

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package php provides the standalone php grammar.
package php

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "14e9b959c3eaa90aa103b92eeec4b2d2eb1f3030fbb5df8f34b28e13afb3a5e7"

func init() {
	grammarruntime.RegisterPhpSupport()
	grammarruntime.RegisterBlob("php", grammarblobs.Php)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("php.bin") }
