//go:build !grammar_subset || grammar_subset_http

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package http provides the standalone http grammar.
package http

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "210ccc7c6aa139ad7eadd1831f1c001ee01391ea579e30571bd419eac369c995"

func init() { ; grammarruntime.RegisterBlob("http", grammarblobs.Http) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("http.bin") }
