//go:build !grammar_subset || grammar_subset_http

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package http provides the standalone http grammar.
package http

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "332d50a15b3facb407f6c449fe8bbcd2fda55efffefbfd4d8d9ce2c75fbb7bda"

func init() { ; grammarruntime.RegisterBlob("http", grammarblobs.Http) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("http.bin") }
