//go:build !grammar_subset || grammar_subset_vimdoc

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package vimdoc provides the standalone vimdoc grammar.
package vimdoc

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "6c45acb52437ba85557b34a552bffbaa8239fa89f36476d49a7c51545fd3f697"

func init() { ; grammarruntime.RegisterBlob("vimdoc", grammarblobs.Vimdoc) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("vimdoc.bin") }
