//go:build !grammar_subset || grammar_subset_templ

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package templ provides the standalone templ grammar.
package templ

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "317ce0e2910b608a9b5bae2657bee9b5ccd27f42937045fd939585dfc4c40593"

func init() {
	grammarruntime.RegisterTemplSupport()
	grammarruntime.RegisterBlob("templ", grammarblobs.Templ)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("templ.bin") }
