//go:build !grammar_subset || grammar_subset_templ

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package templ provides the standalone templ grammar.
package templ

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "78f20ce45f9a4df12c458aadfbe9a98c80572bb13e0e2d01ffc43060e8d04701"

func init() {
	grammarruntime.RegisterTemplSupport()
	grammarruntime.RegisterBlob("templ", grammarblobs.Templ)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("templ") }
