//go:build !grammar_subset || grammar_subset_mermaid

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package mermaid provides the standalone mermaid grammar.
package mermaid

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "568ba4b75dc906aef0efa3349cfa2814629b10b4de3b6da5c934da12888a6449"

func init() { ; grammarruntime.RegisterBlob("mermaid", grammarblobs.Mermaid) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("mermaid.bin") }
