//go:build !grammar_subset || grammar_subset_linkerscript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package linkerscript provides the standalone linkerscript grammar.
package linkerscript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "38f6b3919929cc6408188d5cea64ed0db2ceb7b51e5b560db4a23cddc29e7ad5"

func init() { ; grammarruntime.RegisterBlob("linkerscript", grammarblobs.Linkerscript) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("linkerscript.bin") }
