//go:build !grammar_subset || grammar_subset_linkerscript

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package linkerscript provides the standalone linkerscript grammar.
package linkerscript

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "2a7a3ae1e6e5a6e787894b4eade540d94b907b1588846a3d4b1a37944935425d"

func init() { ; grammarruntime.RegisterBlob("linkerscript", grammarblobs.Linkerscript) }

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("linkerscript") }
