//go:build !grammar_subset || grammar_subset_luau

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package luau provides the standalone luau grammar.
package luau

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "8127890afc23e04bbf0f1b0d6465e42e127b017ce8a3fd9bff0fe4102f3f0d95"

func init() {
	grammarruntime.RegisterLuauSupport()
	grammarruntime.RegisterBlob("luau", grammarblobs.Luau)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("luau.bin") }
