//go:build !grammar_subset || grammar_subset_toml

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-toml 342d9be207c2dba869b9967124c679b5e6fd0ebe src/parser.c

package grammarruntime

// tomlExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var tomlExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false},
	/* 1 */ {true, true, true, true, true},
	/* 2 */ {false, true, true, false, false},
	/* 3 */ {false, false, false, true, true},
	/* 4 */ {true, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("toml", tomlExternalLexStates)
}
