//go:build !grammar_subset || grammar_subset_odin

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package odin provides the standalone odin grammar.
package odin

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "9b376bcbbe677780b9031ae84eee4fb59eb37a14fbe169c7c17d35f2b5b776ed"

func init() {
	grammarruntime.RegisterOdinSupport()
	grammarruntime.RegisterBlob("odin", grammarblobs.Odin)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("odin") }
