//go:build !grammar_subset || grammar_subset_odin

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package odin provides the standalone odin grammar.
package odin

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "681944832361c3b7939a5dcfb9b4b2b19b44cd9cb3a73cacea4d79e84ef9461d"

func init() {
	grammarruntime.RegisterOdinSupport()
	grammarruntime.RegisterBlob("odin", grammarblobs.Odin)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("odin.bin") }
