//go:build !grammar_subset || grammar_subset_less

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package less provides the standalone less grammar.
package less

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "3dd14240e450481efcd66260dcf32eaf4f6b7d88496632ee6c83081014fde9ee"

func init() {
	grammarruntime.RegisterLessSupport()
	grammarruntime.RegisterBlob("less", grammarblobs.Less)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("less.bin") }
