//go:build !grammar_subset || grammar_subset_less

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package less provides the standalone less grammar.
package less

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "457c1e82541ec365592d096ac07e9c853e37823cd72792968e1477df5fae6ed0"

func init() {
	grammarruntime.RegisterLessSupport()
	grammarruntime.RegisterBlob("less", grammarblobs.Less)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("less") }
