//go:build !grammar_subset || grammar_subset_janet

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package janet provides the standalone janet grammar.
package janet

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "7cd2bdbc4df581ff6716cac3ecca9d6d3b22e7ce094c19e11b430900bb81a8e1"

func init() {
	grammarruntime.RegisterJanetSupport()
	grammarruntime.RegisterBlob("janet", grammarblobs.Janet)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("janet") }
