//go:build !grammar_subset || grammar_subset_fish

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package fish provides the standalone fish grammar.
package fish

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "343be0686341a859d99d0a80b6858039fee521530214448a362124de7b343f4d"

func init() {
	grammarruntime.RegisterFishSupport()
	grammarruntime.RegisterBlob("fish", grammarblobs.Fish)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("fish.bin") }
