//go:build !grammar_subset || grammar_subset_fish

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.
// Package fish provides the standalone fish grammar.
package fish

import (
	"github.com/odvcencio/gotreesitter"
	grammarblobs "github.com/odvcencio/gotreesitter/grammars/grammar_blobs"
	grammarruntime "github.com/odvcencio/gotreesitter/grammars/runtime"
)

// BlobSHA256 identifies the packaged grammar artifact.
const BlobSHA256 = "a49e3e1792f8131e94a8ca830bbe235a97b644b2ce7b8be0448a7619ea9d479b"

func init() {
	grammarruntime.RegisterFishSupport()
	grammarruntime.RegisterBlob("fish", grammarblobs.Fish)
}

// Language returns the cached grammar with its scanner and certified runtime profile.
func Language() *gotreesitter.Language { return grammarruntime.Language("fish.bin") }
